angular/dev-infra

github-actions/lock-closed/lib/bundle.js
The underlying issue will be fixed directly in the next release of the package. https://github.com/actions/toolkit/pull/101
=> fix(github-actions): manual workaround for conditional require bug in `@actions/github` package

github-actions/lock-closed/lib/bundle.js, github-actions/lock-closed/package.json, github-actions/lock-closed/src/main.ts
This is necessary as a workaround for https://github.com/actions/toolkit/issues/106
=> use @octokit/rest directly

github-actions/lock-closed/lib/bundle.js, github-actions/lock-closed/src/main.ts
We should lock PRs as well as that is what our policy doc says we are doing.
=> lock prs too

github-actions/feature-request/lib/bundle.js, github-actions/feature-request/src/action.ts, github-actions/feature-request/src/octokit.ts
- Consistent logging by prefixing IDs with `#`
- Add a message when we start and end processing a given issue
=> feat: improve logging in the feature request triage bot

.github/workflows/feature-request.yml, github-actions/feature-request/BUILD.bazel, github-actions/feature-request/bundle.js, github-actions/feature-request/src/get-input.spec.ts, github-actions/feature-request/src/get-input.ts, github-actions/feature-request/src/main.ts
The input parser was not processing properly negative numbers, which was
causing the bot to exit early.
=> fix: proper parsing of input parameters

bazel/BUILD.bazel, bazel/browsers/chromium/BUILD.bazel, bazel/browsers/chromium/chromium.bzl, bazel/browsers/chromium/find-stable-revision-for-all-platforms.ts, bazel/browsers/firefox/BUILD.bazel, bazel/browsers/firefox/firefox.bzl, bazel/constraints/BUILD.bazel, package.json, yarn.lock
Work in progress. Blocked on `rules_webtesting` not shipping darwin ARM64 binaries
=> feat(bazel): support browsers for m1 platform

ng-dev/pr/merge/strategies/autosquash-merge.ts
Because our autosquash merge strategy relies on the fact that  Github automatically closes PRs whose commits
are included in the primary branch.  The commits are closed rather than merged without clear indication to
the PR author that their PR has been in fact merged, rather than just closed. Instead we will now add a
comment to the PR expressing that the PR has actually been merged.
See https://github.com/josephperrott/dev-infra/pull/18#issuecomment-920465024 as example of comment created.
=> feat(ng-dev/pr): include comment for PR merges on all autosquashed merges

bazel/browsers/browser_toolchain_alias.bzl, bazel/browsers/chromium/BUILD.bazel, bazel/browsers/firefox/BUILD.bazel, bazel/integration/tests/angular-cli/BUILD.bazel, bazel/integration/tests/angular-cli/angular.json, bazel/integration/tests/angular-cli/package.json, bazel/integration/tests/angular-cli/test/specs/example.e2e.ts, bazel/integration/tests/angular-cli/test/specs/tsconfig.json, bazel/integration/tests/angular-cli/test/wdio.conf.js, bazel/integration/tests/angular-cli/yarn.lock
=> feat(bazel): expose browser driver binaries through toolchain aliases

.prettierignore, .yarnrc
Update to the latest version of yarn, 1.22.17.
=> build: update to yarn v1.22.17

.bazelrc, bazel/browsers/browser_toolchain_alias.bzl, bazel/integration/test_runner/bazel.ts, bazel/integration/test_runner/runner.ts, bazel/integration/tests/custom_env_variables/BUILD.bazel, bazel/integration/tests/custom_env_variables/test.js, tools/generate_ts_proto_module.bzl
=> fix(bazel): integration rule not working with legacy external runfiles disabled

bazel/benchmark/component_benchmark/component_benchmark.bzl, bazel/benchmark/component_benchmark/defaults/BUILD.bazel, bazel/benchmark/component_benchmark/defaults/index-template.html, bazel/benchmark/component_benchmark/defaults/index.ts, bazel/benchmark/component_benchmark/start-server.js, bazel/benchmark/component_benchmark/test/BUILD.bazel, bazel/benchmark/component_benchmark/test/app.module.ts, bazel/benchmark/component_benchmark/test/app.perf.spec.ts, bazel/benchmark/component_benchmark/tsconfig-e2e.json, bazel/benchmark/driver-utilities/perf_util.ts, tsconfig.json
=> fix(bazel/benchmark): switch to http-server for perf tests to support Apple M1

bazel/benchmark/component_benchmark/component_benchmark.bzl
In the default entry-point index, `zone.js` is imported in a way that is not
checked by TypeScript. We add the dependency only for bundling to reduce the compilation
scope and to make it easier to replace this dependency inside the `angular/angular`
repository with its corresponding source target that does not come with any typings.
Replacing `@npm//zone.js` with a plain source file in the FW repo, or pointing
it to a `js_library` does not work because `ng_module`/`ts_library` would then
complain about a dependency that does not provide any typings. Hence the solution
to that problem is just adding zone.js as dependency for bundling (it's not needed
for the TS compilation anyway). In this repo, zone.js can be a simple dep for `ng_module`
or `ts_library` because it's covered as an …
=> refactor(bazel/benchmark): make it easier to substitute zone.js target with source target

ng-dev/format/formatters/prettier.ts, tools/local-actions/changelog/main.js
This should help making editing of the very few Yaml files (like the CircleCI config) easier 😄
=> feat(ng-dev): format yaml files with prettier by default

github-actions/slash-commands/main.js, ng-dev/pr/common/fetch-pull-request.ts, tsconfig.json
=> fix(ng-dev): avoid runtime error when pull request does not have status/checks

github-actions/commit-message-based-labels/main.js, github-actions/slash-commands/main.js, ng-dev/misc/cli.ts, ng-dev/misc/new-main-branch/cli.ts, ng-dev/misc/new-main-branch/find-local-branch.ts, ng-dev/misc/new-main-branch/remote-fork-update.ts, ng-dev/misc/new-main-branch/remotes.ts, ng-dev/utils/git/authenticated-git-client.ts, ng-dev/utils/git/git-client.ts, ng-dev/utils/git/github-yargs.ts, tools/local-actions/changelog/main.js
See details in:
https://docs.google.com/document/d/1nqb94eSIcGuPC0M9Rv7-IeqOiJKzsMnuistHZNeUmAg/edit#
=> feat(ng-dev): add migration command for master branch rename

ng-dev/pullapprove/BUILD.bazel, ng-dev/pullapprove/condition_errors.ts, ng-dev/pullapprove/condition_evaluator.ts, ng-dev/pullapprove/group.ts, ng-dev/pullapprove/pullapprove_arrays.ts, ng-dev/pullapprove/verify.spec.ts
Necessary change for: https://github.com/angular/angular/pull/44866
=> feat(ng-dev/pullapprove): handle references to `author` in condition

apps/shared/models/app-models.ts, apps/shared/models/check.ts, apps/shared/models/label.ts, apps/shared/models/milestone.ts, apps/shared/models/pull-request.ts, apps/shared/models/server-models.ts, apps/shared/models/status.ts, apps/shared/models/team.ts, apps/shared/models/user.ts
Use proper constructor types as the base for the `BaseModel` typings in mixins to improve the generated types.
=> refactor(apps): improve the model mixin functions to provide more accurate typings

apps/prs/src/app/pr-table/columns/base.ts, apps/prs/src/app/pr-table/pr-table.component.html, apps/prs/src/app/pr-table/pr-table.component.spec.ts, apps/prs/src/app/pr-table/pr-table.component.ts, apps/prs/src/app/pr-table/pr-table.module.ts
Create a table and base column definition for the pull request table to allow for the table columns to
be established incramentally.
=> feat(apps): create the base of the pull request table

bazel/integration/test_runner/runner.ts, ng-dev/release/stamping/env-stamp.ts
=> refactor(ng-dev): improve stamping for snapshot releases 

apps/prs/src/app/pr-table/columns/columns.module.ts, apps/prs/src/app/pr-table/columns/status/status.component.html, apps/prs/src/app/pr-table/columns/status/status.component.scss, apps/prs/src/app/pr-table/columns/status/status.component.ts, apps/prs/src/app/pr-table/pr-table.component.ts, apps/shared/models/base.ts, apps/shared/models/pull-request.ts
=> Create a status column

apps/functions/githubWebhook/BUILD.bazel, apps/functions/githubWebhook/index.ts, apps/functions/githubWebhook/label.ts, apps/functions/githubWebhook/status.ts, apps/shared/models/server-models.ts, apps/shared/models/status.ts
=> Add additional webhooks for Github events

apps/BUILD.bazel, apps/account-functions/BUILD.bazel, apps/account-functions/before-create.ts, apps/account-functions/before-sign-in.ts, apps/account-functions/index.ts, apps/firebase.json, apps/functions/dist, apps/functions/package.json, apps/shared/account/account.service.ts, package.json, yarn.lock
=> Set up user account related things for user creation, login and authentication.

apps/prs/src/app/pr-table/columns/columns.module.ts, apps/prs/src/app/pr-table/columns/target/target.component.html, apps/prs/src/app/pr-table/columns/target/target.component.scss, apps/prs/src/app/pr-table/columns/target/target.component.ts, apps/prs/src/app/pr-table/pr-table.component.ts, apps/prs/src/models/pull-request.ts, apps/shared/models/app-models.ts, apps/shared/models/base.ts, apps/shared/models/pull-request.ts, apps/shared/models/server-models.ts
=> Create target column

github-actions/post-approval-changes/lib/main.ts, github-actions/post-approval-changes/main.js
=> Add additional logging to post approval github action

ng-dev/pr/checkout/cli.ts, ng-dev/pr/cli.ts, ng-dev/pr/discover-new-conflicts/cli.ts, ng-dev/pr/rebase/cli.ts
=> Misc fixes in ng-dev pr toolset 

bazel/browsers/browser_archive_repo.bzl
This will be useful for: https://github.com/angular/dev-infra/issues/604.
=> feat(bazel/browsers): add support for excluding files from browser runfiles

ng-dev/release/publish/actions/cut-stable.ts, ng-dev/release/publish/test/common.spec.ts
When we previously cut v14, it was not quite obvious to the caretaker
that the cut-stable action will publish to `@next` first (as it was
requested/required by the release checklist).
cc. @alxhub
=> refactor(ng-dev/release): indicate that a major stable release is first cut as `@next`

circleci-orb/commands/rebase-on-target-branch.yml, circleci-orb/scripts/rebase-on-target-branch/index.ts
Create a common orb for rebasing pull requests as part of our ci process.
=> feat(circleci-orb): create orb command for rebasing pull requests on the target branch

.github/ng-renovate/runner-config.js
=> build: enable self-hosted angular renovate runner

.github/ng-renovate/package.json, .github/ng-renovate/yarn.lock
Contains a fix we need:
https://github.com/renovatebot/renovate/pull/16451.
=> build: update renovate to work with nested workspaces

bazel/integration/test_runner/runner.ts, bazel/integration/tests/angular-cli/BUILD.bazel, bazel/integration/tests/custom_env_variables/test.js, bazel/integration/tests/nested_bazel_workspaces/BUILD.bazel, bazel/integration/tests/package_mappings/BUILD.bazel, bazel/integration/tests/playwright_chromium/BUILD.bazel
=> Integration misc improvements

github-actions/org-file-sync/main.js, github-actions/org-file-sync/src/main.ts
=> Updates for org-file-sync action

.github/ng-renovate/runner-config.js
Add the .github repo to renovate as we want to manage the github-actions via renovate in that repository.
=> build: add .github repo to list of renovate managed repos

github-actions/create-pr-for-changes/main.js
=> fix(github-actions): update generated `main.js` for `create-pr-for-changes` GitHub Action

bazel/filter_outputs.bzl
=> feat(bazel): add a rule to filter the first matching output

bazel/browsers/chromium/chromium.bzl
=> fix(bazel/browsers): exclude chromium debug logs on remaining platforms

github-actions/google-internal-tests/action.yml, github-actions/google-internal-tests/lib/main.ts, github-actions/google-internal-tests/main.js
This is similar to how it's done in the Github Robot currently.
=> feat(github-actions): support exclusion of files in google-internal-tests` action

.github/local-actions/changelog/main.js, bazel/esbuild/index.bzl, github-actions/commit-message-based-labels/main.js, github-actions/create-pr-for-changes/main.js, github-actions/feature-request/main.js, github-actions/google-internal-tests/action.yml, github-actions/google-internal-tests/lib/BUILD.bazel, github-actions/google-internal-tests/lib/main.ts, github-actions/google-internal-tests/main.js, github-actions/labels-sync/main.js, github-actions/lock-closed/main.js, github-actions/org-file-sync/main.js, github-actions/post-approval-changes/main.js, github-actions/slash-commands/main.js, ng-dev/caretaker/BUILD.bazel, ng-dev/caretaker/check/base.ts, ng-dev/caretaker/check/g3.spec.ts, ng-dev/caretaker/check/g3.ts, ng-dev/caretaker/config.ts, ng-dev/caretaker/g3-sync-config.ts, package.json, yarn.lock
=> fix(ng-dev): update caretaker check to support canonical config for g3 sync

.gitignore, bazel/api-golden/index.ts, bazel/api-golden/index_npm_packages.ts, bazel/api-golden/test_api_report.ts, bazel/http-server/BUILD.bazel, bazel/http-server/server.ts, bazel/integration/test_runner/main.ts, bazel/map-size-tracking/index.ts
=> feat(bazel): avoid TS code relying on CommonJS-specific features 

.github/ng-renovate/runner-config.js
More context: https://github.com/renovatebot/renovate/issues/16657
https://github.com/renovatebot/renovate/commit/340a913a48bca375d721cf59bde3fe7a14ed6f1c
=> build: never allow renovate PRs to be edited directly

ng-dev/release/publish/actions/index.ts, ng-dev/release/publish/actions/special/cut-lts-minor.ts
Needs for publishing the optimize directive backported to v14, v13 and v12.
=> feat(ng-dev): support special action to cut lts minor release

.github/local-actions/branch-manager/main.js, .github/local-actions/changelog/main.js, .github/ng-renovate/package.json, .github/ng-renovate/yarn.lock, bazel/http-server/index.bzl, bazel/http-server/main.ts, bazel/map-size-tracking/test/size-golden.json, github-actions/branch-manager/main.js, github-actions/commit-message-based-labels/main.js, github-actions/create-pr-for-changes/main.js, github-actions/deploy-previews/upload-artifacts-to-firebase/extract-artifact-metadata.js, github-actions/feature-request/main.js, github-actions/google-internal-tests/main.js, github-actions/labels-sync/main.js, github-actions/lock-closed/main.js, github-actions/org-file-sync/main.js, github-actions/post-approval-changes/main.js, github-actions/slash-commands/main.js, github-actions/unified-status-check/main.js, ng-dev/utils/ng-dev-service.ts, yarn.lock
=> build: update all non-major dependencies

github-actions/create-pr-for-changes/lib/main.ts, github-actions/create-pr-for-changes/main.js
Fixes errors like:
https://angular-team.slack.com/archives/C042EU9T5/p1682064243477639
=> fix(github-actions): gracefully attempt to delete PR branches

.github/local-actions/branch-manager/main.js, github-actions/slash-commands/main.js, ng-dev/pr/common/fetch-pull-request.ts, ng-dev/pr/common/validation/assert-isolated-separate-files.ts, ng-dev/utils/github.ts
This fixes the improperly formed graphql query to retrieve PR files and paginate through them
=> fix(ng-dev): Fixes graphql query for pr files

.github/ng-renovate/package.json, .github/ng-renovate/yarn.lock
Test if this fixes an issue which casues the groups not to work.
=> build: update renovate to `38.9.0`

.github/local-actions/branch-manager/main.js, github-actions/create-pr-for-changes/main.js, ng-dev/utils/child-process.ts
This is a small regression introduced via:
https://github.com/angular/dev-infra/commit/933dcd42f8837d6d6ce3a28419a760edb94f10e6
=> fix(ng-dev): properly pass `input` to `stdin` of child processes

bazel/api-golden/index.bzl
Currently multiple `package.json` files are generated in the same Bazel package, causing Bazel conflicts.
Needed for the Material migration.
=> fix(bazel): support multiple `api_golden_test` targets in the same Bazel package

github-actions/post-approval-changes/lib/main.ts, github-actions/post-approval-changes/main.js
It seems that we no longer have an installation on a specific repository, but checking via the still-active organization installation should be sufficient. This commit attempts this.
Also adds a graceful mode where we rely on public membership if no access token can be retrieved. This has positive impact on our security responsibilities.
=> fix: only request org installation for `googlers` organization

.github/workflows/ng-renovate.yml
=> ci: bump renovate pnpm to `9.15.9`

.npmrc
=> build: create an `.npmrc`

renovate-presets/default.json5
One less thing to do for users.
=> fix(github-action): replace `action: review` with `action: merge` in renovate preset

.github/ng-renovate/package.json, .github/ng-renovate/yarn.lock
This reverts commit e368807b1f150c26e5cea5fce3efdaf6633b591f.
=> revert "build: update dependency renovate to v40.18.3"

github-actions/setup-wsl/action.yml
Fixes windows CI due to https://github.com/Vampire/setup-wsl/issues/76
=> fix(github-actions): use ubuntu instead of debian

renovate.json
Adds the bazel lock file update command to post update task
=> ci: add bazel lock file update command
