angular/dev-infra

- github-actions/lock-closed/src/main.ts
Previously, the policy URL used in the automatic conversation locking comment used a shortened SHA (6 our of 40 chars). Such SHAs only work as long as there is no other SHA in the repo starting with the same chars. Since there are now two SHAs starting with the same 6 chars, the link is broken and resulrts in a 404 error. Example: https://github.com/angular/angular-cli/issues/18058#issuecomment-673948687
This commit fixes the broken link by using the full SHA (40 chars).
> fix(lock-closed): fix broken policy URL

- github-actions/lock-closed/action.yml
- github-actions/lock-closed/lib/bundle.js
- github-actions/lock-closed/package.json
This PR includes three fixes. See the individual commits for more details:
- **fix(lock-closed):** update `policyUrl` in `bundle.js`
- **fix(lock-closed):** fix `main` field in `package.json`
- **docs(lock-closed):** update `inputs` in `action.yml` (github-token --> lock-bot-token)
(This PR will help address angular/angular#39358.)
> fix(lock-closed): update `policyUrl` in `bundle.js`

- github-actions/lock-closed/action.yml
**Why**:
To remove this warning from the Github Action:
`Warning: Unexpected input(s) 'lock-bot-key', valid inputs are ['lock-bot-token', 'locks-per-execution']`
(see it happening [here](https://github.com/angular/angular/runs/1614331849?check_suite_focus=true))
**But in the end, it is lock-bot-token or lock-bot-key?**
It is *lock-bot-key* for sure as it shows [here](https://github.com/angular/angular/blob/master/.github/workflows/lock-closed.yml#L15) and [here](https://github.com/gkalpak/dev-infra/blob/master/github-actions/lock-closed/src/main.ts#L47).
**TODO after merging:**
To update the commit hash [here](https://github.com/angular/angular/blob/master/.github/workflows/lock-closed.yml#L13)
> fix the warning: Warning: Unexpected input(s) 'lock-bot-key'

- github-actions/feature-request/action.yml
- github-actions/feature-request/lib/bundle.js
- github-actions/feature-request/src/action.spec.ts
- github-actions/feature-request/src/action.ts
- github-actions/feature-request/src/main.ts
- Add more context in the heads up comment for old issues
- Make sure we don't comment twice on issues with insufficient number of votes
- Set a limit configuration property to allow us go through only a limited number of issues
> Improve comment content and comment mechanism

- ng-dev/pr/merge/defaults/integration.spec.ts
- ng-dev/release/build/build.spec.ts
- ng-dev/release/config/index.ts
- ng-dev/release/notes/context.ts
- ng-dev/release/notes/release-notes.ts
- ng-dev/release/notes/templates/changelog.ts
- ng-dev/release/notes/templates/github-release.ts
- ng-dev/release/publish/test/common.spec.ts
- ng-dev/release/publish/test/cut-lts-patch.spec.ts
- ng-dev/release/publish/test/release-notes/context.spec.ts
- ng-dev/release/publish/test/release-notes/generation.spec.ts
- ng-dev/release/publish/test/test-utils/action-mocks.ts
- ng-dev/release/publish/test/test-utils/git-client-mock.ts
- ng-dev/release/set-dist-tag/set-dist-tag.spec.ts
Various improvements for release notes. See individual commits.
> refactor(ng-dev): move breaking change and deprecations to beginning of release notes

- ng-dev/release/publish/test/test-utils/action-mocks.ts
Bazel expects tests "not attempt to remove, chmod, or otherwise alter [TEST_TMPDIR]," so instead a subdirectory
should be used to be created/destroyed throughout tests.  If the TEST_TMPDIR is directly used the first usage
works as expected but removing the directory is not successful causing failure on the next creation.  This
failure does not occur on windows due to Bazel's lack of sandboxing and therefore lack of control over the
interactions with the TEST_TMPDIR.
> test(ng-dev): fix usage of TEST_TMPDIR

- BUILD.bazel
This is a temporary fix to ensure that the husky install is not included in the package.json for the published npm package.
> fix: remove husky install from `scripts` section of package json for published npm package

- ng-dev/release/notes/context.ts
- ng-dev/release/notes/release-notes.ts
- ng-dev/release/notes/templates/changelog.ts
- ng-dev/release/notes/templates/github-release.ts
- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/constants.ts
- ng-dev/release/publish/test/common.spec.ts
- ng-dev/release/publish/test/test-utils/github-api-testing.ts
- ng-dev/utils/git/github-urls.ts
While manually testing the release tool a couple of times
for the COMP and FW repos, the script sometimes failed
based on the release notes comparison range. i.e. if
there were too many changes in the release notes, the
Github API errored out when we send the `POST` http
request for creating the Github release entry.
Github does not seem to give official details about
the limits on the release body property. The limit
seems to be between 25k and 125k. This is surprising
but based on actual testing. Initially I was seeing failures
with 25k characters limit, but today (8/17/2021) the limit
seems to be (for all my forks; also organization repos) set
to 125k. I think it's best to stay with the lowest we have
seen. If we exceed, we just link to the changelog, assuming it
still exists in the …
> fix(ng-dev): release fails if release notes are too long

- tools/local-actions/changelog/lib/main.ts
- tools/local-actions/changelog/main.js
We accidentally used `getDay` instead of `getDate` for
constructing the changelog version.
> build: fix changelog action constructing incorrect version

- ng-dev/pr/check-target-branches/check-target-branches.ts
- ng-dev/pr/merge/config.ts
- ng-dev/pr/merge/defaults/integration.spec.ts
- ng-dev/pr/merge/defaults/labels.ts
- ng-dev/pr/merge/failures.ts
- ng-dev/pr/merge/fetch-pull-request.ts
- ng-dev/pr/merge/pull-request.ts
- ng-dev/pr/merge/target-label.ts
- ng-dev/pr/merge/validations.ts
Instead of hard-coding the label names for the target labels
the whole Angular organization uses, we now have an enum for
these names, allowing for consistent use of the labels.
This is in preparation for adding the proper target labels
automatically to staging and cherry-pick release PRs. Previously
this was not possible because we still had a possible way to configure
custom target labels, and missed such an enum.
This new enum came together with some refactorings that cleaned up
some of the validation and target label extraction logic. Mostly code
has been split up into individual files, allowing for more readable code
and less convuluted files.
**Note**: This also fixes `yarn ng-dev pr check-target-branches` if target labels are disabled.
> refactor(ng-dev): create enum for target label names

- ng-dev/release/publish/actions.ts
The release notes compare tag might not exist locally if the local
repository has not been synced with upstream. We fetch the release
notes compare tag in order to be able to build the changelog. Our
current fetch logic incorrectly stores the tag reference in
`FETCH_HEAD`, while we want it to be stored locally. This commit
fixes that.
> fix(ng-dev/release): fetch release notes compare tag and store it locally

- bazel/benchmark/ng_rollup_bundle/ng_rollup_bundle.bzl
- bazel/benchmark/ng_rollup_bundle/terser_config.json
Supports for terser v5 in the `ng_rollup_bundle` rule. currently
terser fails because there is a conflicting `--beautify` CLI flag
set by `@bazel/terser` and the `output` option we manually control.
Instead of `output`, the new non-conflicting `format` name should be used:
```
ERROR: Please only specify either output or format option, preferrably
format.
```
> feat(bazel): support for terser v5 and 2020 in rollup_bundle rule

- github-actions/slash-commands/main.js
- ng-dev/pr/rebase/index.ts
- tools/local-actions/changelog/lib/main.ts
- tools/local-actions/changelog/main.js
Previously we used `--depth` to ensure that enough commits were included in the repository to effectively
perform actions.  However, using `--depth` sets the depth of the repository, and if the repository previously
was unshallow, it because a shallow repository.  Instead by using deepen, the depth will be increased by the
provided value.  This will ensure that the enough commits are included and will be a noop if an unshallow
repo is deepened further.
> fix: use --deepen in place of --depth during fetches

- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/index.ts
The `prepare-commit-message` hook can still accidentally run when the
changelog / version bump commit is created. This is problematic because
when a version branch is checked out (like the patch branch), the node
modules are not necessarily updated/re-installed, and the node modules
from master remain installed. This can cause runtime errors when Git
hooks accidentally run with a tool from the node modules (like `ng-dev`
itself).
We fix this by also setting the `HUSKY` environment variable, similar to
how the merge tool does. We can assume that Husky is used in all
repositories. This should be our standard for hooks.
> fix(ng-dev/release): prepare-commit-message hook accidentally running when bump commit is created

- ng-dev/pr/common/targeting/labels.ts
If a project does not have a release configuration defined, the LTS branches cannot be determined
and should not be included in the target labels when determined.
> fix(ng-dev): only include LTS label as a target label if the release configuration is defined

- ng-dev/release/publish/actions/tag-recent-major-as-latest.ts
The `TagRecentMajorAsLatest` action errantly said it was tagging the version as `next` when it tags it as `latest`.
> fix(ng-dev/release): fix description for TagRecentMajorAsLatest action

- .ng-dev/commit-message.ts
- tslint-rules/validateImportForEsmCjsInteropRule.ts
> feat(tslint-rules): move validate-import-for-esm-cjs-interop from framework

- bazel/browsers/browser_configure.bzl
- bazel/browsers/browser_toolchain_alias.bzl
- bazel/browsers/chromium/BUILD.bazel
- bazel/browsers/firefox/BUILD.bazel
- bazel/integration/index.bzl
- bazel/integration/test_runner/bazel.ts
- bazel/integration/test_runner/process_utils.ts
- bazel/integration/test_runner/runner.ts
- bazel/integration/tests/angular-cli/BUILD.bazel
- bazel/integration/tests/angular-cli/karma.conf.js
- bazel/integration/tests/angular-cli/package.json
- bazel/integration/tests/angular-cli/yarn.lock
See individual commits. Allows us to use Chromium from Bazel, instead of having to always manage/install puppeteer for Browser-based integration tests.
> Allow integration test rules to access browser binaries managed within Bazel

- bazel/integration/index.bzl
- bazel/integration/test_runner/main.ts
- bazel/integration/test_runner/runner.ts
- bazel/integration/tests/external_command_script/BUILD.bazel
- bazel/integration/tests/external_command_script/external_script.sh
Given a tool built using `nodejs_binary` or `sh_binary`, the tool cannot
be used as binary in an integration test command currently because:
* Bazel location expansion does not respect the executable "FilesToRun"
information of the binaries, and rather sees _all_ outputs, erroring
that `$(locations X)` need to be used instead. See e.g. https://github.com/bazelbuild/bazel/issues/11820)
* The command is currently split by space and this decouples the Make
funtion expression incorrectly into a broken expansion. e.g.
`$(rootpath X)` will become `["$(rootpath", "X"]`).
This commit fixes both things by relying on the Bazel
`CommandHelper.java` class which handles the expansion of commands as
expected, with similar semantics of a `genrule` as per `GenRuleBase.java`.
This allows test authors to …
> feat(bazel): allow integration commands to resolve executables through expansion

- .bazelrc
- .circleci/config.yml
- BUILD.bazel
- ng-dev/release/publish/BUILD.bazel
- ng-dev/release/publish/constants.ts
- ng-dev/release/publish/external-commands.ts
- ng-dev/release/publish/index.ts
- ng-dev/release/publish/yarn-lock-file.d.ts
- ng-dev/release/stamping/env-stamp.ts
- ng-dev/utils/constants.ts
- package.bzl
- package.json
- tools/BUILD.bazel
- yarn.lock
Fixes that the ng-dev release tool currently relies on a historically broken
`yarn check` command for ensuring it is up-to-date. This check has proven to
not work well within the Angular repositories, so we switch to a more future-proof
and reliable approach by checking the lock file and comparing with the running
version through a substitued placeholder.
> fix(ng-dev/release): properly ensure local ng-dev version is up-to-date

- .circleci/config.yml
Set up the OSS abuse orb provided to use by CircleCI to monitor build frequency on angular/angular.
Orb information can be found at: https://circleci.com/developer/orbs/orb/oss-tools/buildalert
The previous attempt failed to work as expected due to the wrong type of API key being used.  This fix as been verified to work as seen [here](https://app.circleci.com/pipelines/github/angular/dev-infra/691/workflows/e3d71b65-ad21-4342-a4c2-7a8f55f1fee0).
> ci: set up OSS abuse orb to monitor usage on the angular/angular repo

- package.bzl
- shared-scripts/BUILD.bazel
- shared-scripts/README.md
In order to simplify the use of the shared scripts within the dev-infra
repo itself, and within consumer projects, while also improving the
dependency managment and runfile tree creation, we start shipping the
actual `BUILD.bazel` files for the shared scripts.
This allows us to just continue using the shared-scripts Bazel targets
within Bazel tools, without needing any substitutions. And it also
ensures that the scripts will have the proper dependencies within Bazel
actions (e.g. by relying on a `js_library`). This also reduces the set
of unnecessary runfiles being brought in as the whole
`@angular/dev-infra-private` package and transitive deps wouldn't be
always needed.
This also works better within the FW repo where e.g.
`@angular/compiler` needs to be resolved through the Bazel NodeJS …
> refactor: ship `BUILD.bazel` files for shared scripts

- shared-scripts/angular-linker/BUILD.bazel
Adds a small workaround for
https://github.com/bazelbuild/rules_nodejs/pull/3083.
Currently it is not possible to expose a `js_library` from an external
workspace and make it work with the linker. The JS library rule always
assumes that files are located in the `bazel-out/<..>/bin` directory.
This is not necessarily true and it would also be inefficient always
copying sources to the bazel-out when they originate from an external
workspace (although that is what we are doing now as a workaround).
> refactor: add workaround for shared-scripts not working with linker

- ng-dev/misc/update-yarn/cli.ts
- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/actions/cut-stable.ts
- ng-dev/release/publish/actions/tag-recent-major-as-latest.ts
- ng-dev/release/publish/external-commands.ts
- ng-dev/release/publish/test/BUILD.bazel
- ng-dev/release/publish/test/common.spec.ts
- ng-dev/release/publish/test/cut-next-prerelease.spec.ts
- ng-dev/release/publish/test/cut-stable.spec.ts
- ng-dev/release/publish/test/tag-recent-major-as-latest.spec.ts
- ng-dev/release/publish/test/test-utils/test-action.ts
- ng-dev/release/publish/test/test-utils/test-utils.ts
- ng-dev/utils/BUILD.bazel
- ng-dev/utils/nodejs-errors.ts
- ng-dev/utils/resolve-yarn-bin.ts
- ng-dev/utils/test/BUILD.bazel
- ng-dev/utils/test/resolve-yarn-bin.spec.ts
- package.json
- yarn.lock
Currently there is one surprising issue within the release tool that
breaks the release of LTS versions.
If the ng-dev release tool is invoked through Yarn. e.g. `yarn ng-dev`,
Yarn will create a temporary directory and create wrappers for a binary
called `yarn` that will directly point to the checked-in Yarn file that
originally invoked the `ng-dev` tool. This means that child processes
calling to `yarn` will actually depend on the checked-in Yarn version
that invoked the `ng-dev` tool.
This logic works fine for most scripts/commands, but it breaks if the
release tool checks out an LTS branch and runs `yarn`. The checked-in
Yarn file from the original invocation may not exist anymore.
We fix this by resolving Yarn directly within the project, falling back
to the NPM global bin, or …
> fix(ng-dev/release): do not error when yarn version of publish branch is older

- bazel/benchmark/app_bundling/index.bzl
This is a new difference that came up accidentally when the
ng_rollup_bundle rule has been reworked. A subset of targets
generated by the `app_bundle` macro is always testonly. This results
in unnecessary/unavoidable churn when the rule is used like in
Angular framework.
> fix(bazel): do not always treat parts of `app_bundle` rule as testonly

- bazel/benchmark/app_bundling/index.bzl
- bazel/benchmark/app_bundling/test/BUILD.bazel
Fixes that no tags can be specified for `app_bundle` benchmark
targets due to a conflict with the debug target and its tags.
> fix(bazel): unable to set tags for `app_bundle` rule due to conflict

- ng-dev/release/publish/external-commands.ts
- shared-scripts/angular-linker/BUILD.bazel
- shared-scripts/angular-optimization/BUILD.bazel
> fix(ng-dev/release): resolved yarn instance not used for "release info" command

- shared-scripts/angular-linker/esbuild-plugin.mjs
Previously `createLinkerEsbuildPlugin` would invoke `createEs2015LinkerPlugin` without any options.
Now options passed into `createLinkerEsbuildPlugin` propagate into the internal invocation of `createEs2015LinkerPlugin`.
> feat(bazel): allow options to be passed into esbuild ng linker plugin for bazel

- renovate.json
We want the Angular dependencies to be updated with the next channel,
so that we can dedupe dependencies as much as possible when the shared
dev-infra package is consumed in sub-Angular repositories.
Also cleans up some of the outdated config settings.
> build: configure renovate to update angular with next channel

- bazel/benchmark/driver-utilities/BUILD.bazel
With the replacement of `node-uuid` to `uuid`, the runtime dependency
on the `uuid` module has been accidentally left out. See:
https://github.com/angular/dev-infra/commit/1638e3ff580204d3b6755ad6cd353a8e8031151d
Fixing errors like:
```
17:43:07] E/launcher - Error: Error: Cannot find module 'uuid'. Please verify that the package.json has a valid "main" entry
at Function.module.constructor._resolveFilename (/b/f/w/bazel-out/k8-fastbuild/bin/modules/benchmarks/src/tree/iv/e2e_chromium.sh.runfiles/angular/modules/benchmarks/src/tree/iv/e2e_wrapped_test_protractor_bin_require_patch.js:481:17)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at …
```
> fix(bazel/benchmark): missing uuid runtime dependency for perf utils

- .circleci/config.yml
- bazel/benchmark/component_benchmark/component_benchmark.bzl
- bazel/benchmark/component_benchmark/test/BUILD.bazel
Explicitly adds the component benchmark rule test to ensure
the tests run. Benchmark targets are marked as `manual` by
default.
> test: ensure benchmark component rule test runs on CI

- .github/workflows/scorecard.yml
We use the main branch, not master.
> build: fix scorecard config

- shared-scripts/angular-linker/esbuild-plugin.mjs
When using the linker on `@angular/material` or packages which contain external sourcemap. The sourcemap will contain multiple sources example.
Babel now uses [remapping](https://github.com/ampproject/remapping/) to merge sourcemaps, see: https://github.com/babel/babel/pull/14209. This doesn't support multiple sources which the linker produduces. Previously, Babel failed silently and didn't generate a sourcemap https://github.com/angular/angular/issues/42769 at all.
Linker produced sourcemap
```js
[
'/packages/web-app-edit/Users/cli-reproductions/monorepo-new/node_modules/@angular/material/fesm2020/card.mjs',
'/packages/web-app-edit/Users/src/material/card/card.html',
'/packages/web-app-edit/Users/src/material/card/card-header.html', …
```
> fix(bazel): disable angular linker sourcemaps

- bazel/http-server/server.ts
It is currently not possible to serve dotfiles (e.g. .stackblitzrc) from the http-server. This PR changes the configuration to allow this.
We understand that this repository is only intended for internal Angular development and in this regard we completely understand if you reject this PR. Still we wanted to ask if you could accept this change, since this PR only changes a small configuration, without having any semantic impact.
> refactor: allow http-server to serve dotfiles

- .ng-dev/commit-message.ts
- bazel/browsers/test/BUILD.bazel
- bazel/karma/index.bzl
Fixes that the webtest arguments are not passed through to the
debug target. Also wires up the rule in our own tests as planned
initially (now that the test is merged)
> fix(bazel/karma): web test arguments not passed through

- bazel/karma/index.bzl
We should re-export the unmodified karma web test macro/rule in the
dev-infra Karma shared code so that a single import in consumer
repositories like framework is sufficient. Currently framework
would need to import from `@bazel/concatjs` and from `dev-infra-private/bazel/karma`
to get access to the Karma Bazel rules/macros.
> feat(bazel/karma): expose karma web test rule in shared karma code

- github-actions/commit-message-based-labels/main.js
- github-actions/slash-commands/main.js
- ng-dev/utils/git/git-client.ts
- tools/local-actions/changelog/main.js
In some cases the `hasUncommittedChanges` check returns false-positives
that occur due to us not refreshing & cleaning up the index before diffing
the index. The index needs a cleanup/refresh when a file is simply touched/modified with the actual content not changing. i.e. just the last modified time got updated.
More details: https://stackoverflow.com/questions/34807971/why-does-git-diff-index-head-result-change-for-touched-files-after-git-diff-or-g/34808299#34808299
> fix(ng-dev): uncommitted changes check returning false-positives

- package.json
Although `@angular/compiler-cli` is a dependency of the [//shared-scripts/angular-linker:js_lib][1] target (and would therefore normally appear in `dependencies`), this was causing error in the framework repo tests: [Example failure][2]
Move `@angular/compiler-cli` to `devDependencies` to allow each consumer provide their own version of the package.
##
NOTE 1: _This is a follow-up to #387._
NOTE 2: _I have verified that the framework repo CI passes with the changes in this PR: [CI run][3]._
[1]: https://github.com/angular/dev-infra/blob/5ae1ce8ee8b11b092e9e5c935eeebec58990edee/shared-scripts/angular-linker/BUILD.bazel#L22
[2]: https://circleci.com/gh/angular/angular/1127275
[3]: https://app.circleci.com/pipelines/github/angular/angular/43061/workflows/c56daf0f-d6c1-4c10-8f90-13f1f19e3fe9
> build: move `@angular/compiler-cli` to `devDependencies`

- .bazelrc
- ng-dev/release/stamping/cli.ts
- package.json
We usually would use the `ng-dev` tool directly for stamping, but that one would need to be
built with Bazel and building with Bazel inside the Bazel-invoked workspace status
script does not work. To workaround this we have a `ts-node`-based stamping script.
> build: fix workspace stamping breaking snapshot publishing

- ng-dev/cli.ts
- ng-dev/index.ts
- ng-dev/release/stamping/_private_main.ts
- ng-dev/release/stamping/cli.ts
- package.json
- tools/defaults.bzl
- yarn.lock
Fixes a couple of typos, cleans up the stamping private entry-point
and adds a trick to make the release checks in COMP work. It looks
like they did not work for quite a while because the `ReleaseAction`
instance being patched as a trick is not the one used by the CLI
used for publishing the release (since we have multiple copies of the release
action constructor in multiple bundles..)
>  Long-term ESM with code splitting would help more (ESBuild only supports code splitting for ESM), but the ESM change involves a lot of caveats (I just tried and remember from APF) -- so now the little workaround exists and the unfortunate duplication of some bundled deps.
> build: fix packaging of dev-infra package

- bazel/remote-execution/cpp/BUILD.bazel
.. so builds can be run locally on non-k8 machines.
Replaces #429
> build: tag cc_toolchain_suite as manual

- .gitignore
- .yarn/yarn.js
- WORKSPACE
More details here: https://github.com/bazelbuild/rules_nodejs/pull/3350.
This commit adds a little wrapper script as temporary workaround to fix CI.
> build: fix yarn install with vendored yarn due to bug in `rules_nodejs`

- ng-dev/release/stamping/env-stamp.ts
Previously we matched on all characters before our semver matching in the glob used for finding
the latest version for the branch we are on.  However when the branch contains something like
`zonejs-1.2.3`, the `*` matcher would capture it, leading to an unexpected syntax.  Instead we should
allow for only a single letter, typically `v`, to prefix our version tags.
cc: @AndrewKushnir
> fix(ng-dev/release): only match on a single character prefixed version for snapshotting

- .bazelrc
- ng-dev/release/stamping/_private_main.ts
- ng-dev/release/stamping/cli.ts
- ng-dev/release/stamping/env-stamp.ts
Some repositories like the `dev-infra` repository do not follow the
usual Angular SemVer versioning but still would like to use the shared
stamping script.
For these repositories, another option is added to the stamping command
that allows version info from being included. There needs to be a way
to disable this as otherwise stamping currently fails when it tries to
find/compute a SemVer version from the workspace `package.json`, causing
errors like:
```
TypeError: Invalid Version: 0.0.0-{SCM_HEAD_SHA}
```
> feat(ng-dev): support skipping version stamp in release stamp env

- ng-dev/index.ts
These classes will be needed for interacting with the release versioning APIs.
> refactor(ng-dev): expose git and github client classes in ng-dev entry-point

- package.json
- yarn.lock
As we start to update TS in all other Angular repos, we should
make sure the shared tooling is also in sync with regards to the
TS version (https://github.com/angular/angular/commit/94bba76a4a9594a5eb90e581f407f1b70697e715)
> build: update to typescript v4.6 to match with FW repo

- WORKSPACE
Enables symlinking of the node modules folder to keep a single
install of NPM/Yarn. More details can be found here:
https://github.com/angular/dev-infra/pull/446#issuecomment-1059820287
Symlinking previously was enabled by default, but as part of RNJ 5 this
has changed without any super-noticable changelog entry.
> build: enable node module symlinking for Bazel

- bazel/extract_js_module_output.bzl
- bazel/spec-bundling/spec-entrypoint.bzl
The `JSModuleInfo` provider is no longer part of the `build_bazel_rules_nodejs` repository
but rather part of the "rules_nodejs" fundamentals. We should no longer rely on the
backwards-compatibility exposed provider, but instead use the expected new import.
> refactor: no longer import `JSModuleInfo` provider through backwards-compat entry

- .circleci/config.yml
https://app.circleci.com/pipelines/github/angular/dev-infra/164070/workflows/cc6cd9a7-5e0f-450c-b839-ece856156796/jobs/165678
@josephperrott I'm proposing to just always set the timeout to 5min (windows takes 3min fresh as it seems), so we could use the shared command and avoid some complexity in the config (as macos 2min also is too short)
> ci: fix yarn install timeout in macos job

- .circleci/config.yml
Looks like the cache key did not contain the `yarn.lock`, which I
assumed it had when I re-enabled the Yarn cache in a previous commit.
> ci: fix cache key to also include `yarn.lock`

- ng-dev/release/notes/context.ts
- ng-dev/release/publish/test/release-notes/generation.spec.ts
- tools/local-actions/changelog/main.js
…
With this change we fix an issue where when breaking changes or deprecations messages contained bullets these were not indented correctly.
Previously
```
- Support for Node.js v12 has been removed as it will become EOL on 2022-04-30. Please use Node.js v14.15 or later.
- Several changes in the Angular CLI commands and arguments handling.
- `ng help` has been removed in favour of the `—-help` option.
- `ng —-version` has been removed in favour of `ng version` and `ng v`.
- Deprecated camel cased arguments are no longer supported. Ex. using `—-sourceMap` instead of `—-source-map` will result in an error.
- `ng update`, `—-migrate-only` option no longer accepts a string of migration name, instead use `—-migrate-only -—name <migration-name>`.
- `—-help json` help has been removed.
| Commit …
```
> fix(ng-dev): correctly indent bullets in breaking changes and deprecations sections

- renovate.json
Renovate is never able to fully/properly update integration
test projects as they are technically invalid (due to e.g.
`file:../../whatever` version installs).
We should just skip these tests as they should rarely need
updates anyway, and since that makes Renovate happy and not
complain about broken updates/invalid artifacts.
> ci: ignore integration test projects in renovate

- bazel/extract_js_module_output.bzl
Use the correct field name (`node_modules_roots` instead of `node_module_roots`) when trying to access data off of the [LinkerPackageMappingInfo][1] value of a dependency in `extract_js_module_output()`.
See [here][2] for an example of a failure with the current incorrect field name.
[1]: https://github.com/bazelbuild/rules_nodejs/blob/2a78e6d815ee36e99cf9cc6462419e16f11c057d/internal/linker/link_node_modules.bzl#L34
[2]: https://circleci.com/gh/angular/angular/1137996
> fix(bazel): use correct `LinkerPackageMappingInfo` field name

- bazel/benchmark/app_bundling/index.bzl
https://github.com/bazelbuild/rules_nodejs/pull/3106
> build: remove workaround for rules_nodejs#3106 which landed in 4.5.0

- ng-dev/pullapprove/condition_evaluator.ts
- ng-dev/pullapprove/pullapprove_arrays.ts
- ng-dev/pullapprove/verify.spec.ts
A few conditions in framework currently rely on the `in` operator. We
should support this even though it potentially going away when we
re-work how global approvals are performed. This makes the verify command
a little more future-proof and currently unblocks the dev-infra update.
It's worth noting that our Python -> JS conversion is very limited but
we can always expand when needed, or start running actual Python. Right
now this captures the most common cases of conditions we have seen across
Angular.
> feat(ng-dev/pullapprove): support `in` operator in condition evaluation

- bazel/api-golden/BUILD.bazel
- bazel/api-golden/index.bzl
- bazel/api-golden/index.ts
- bazel/api-golden/index_npm_packages.ts
- bazel/api-golden/module_mappings.ts
- bazel/api-golden/test/BUILD.bazel
- bazel/api-golden/test/fixtures/test_package/testing/namespace-alias.ts
- bazel/api-golden/test/fixtures/test_package/testing/nested.d.ts
- bazel/api-golden/test/goldens/test_package/testing/nested/index.md
- bazel/api-golden/test_api_report.ts
- package.json
- yarn.lock
Currently the API golden bazel test rule will just add `@types/<..>`
modules to the TSConfig `types` section. This is unreliable and relies
on the Bazel NodeJS linker which does not work well on Windows.
This commit refactors the logic to rely on path mappings for type
resolution inside the API golden Bazel-based tests. This guarantees
a working rule on Windows and also supports scoped packages. Currently
scoped package types do not work, like `@types/babel__core` which is
actually mapping internally to `@babel/core`.
Our trick will be to use path mappings as mentioned before, manually
computing the scoped package types (like with `@babel/core`). Additionally
referenced types will still be loaded directly as part of the compilation
inputs to support global type definitions like …
> feat(bazel/api-golden): allow for module types to be provided

- ng-dev/utils/git/github-yargs.ts
Currently, `token` default to an empty string, which results in always using an empty string as token because `findGithubTokenInEnvironment` will never be invoked.
> fix(ng-dev): fix github token retrieval logic

- apps/functions/githubWebhook/BUILD.bazel
- apps/functions/githubWebhook/pull-request.ts
- apps/shared/models/app-models.ts
- apps/shared/models/base.ts
- apps/shared/models/check.ts
- apps/shared/models/index.ts
- apps/shared/models/label.ts
- apps/shared/models/milestone.ts
- apps/shared/models/pull-request.ts
- apps/shared/models/server-models.ts
- apps/shared/models/status.ts
- apps/shared/models/team.ts
- apps/shared/models/user.ts
Instead of creating a static converter with a mixin, the mixin instead sets methods to get the converter and DocumentReference using the class definition.
> refactor(apps): use static helper methods for getting firestore references and converters

- apps/BUILD.bazel
- apps/firebase.json
- apps/functions/dist
The symlink is invalid when a Github action is cloned because
Bazel did not run yet. We should avoid the symlink to keep our
actions working:
https://github.com/angular/components/runs/6127973017?check_suite_focus=true
> fix(apps): avoid symlink that breaks github action cloning

- ng-dev/misc/new-main-branch/cli.ts
- ng-dev/misc/new-main-branch/local-branch.ts
- ng-dev/misc/new-main-branch/remote-fork-update.ts
After we will perform the default branch rename, there are three scenarios for
a contributor:
1. They manually fetch `upstream/main`, run `yarn` and then the
migration tool.
2. They will not sync with upstream (as `upstream/master` does not
exist), run `yarn` and then the migration tool.
3. They will manually update everything locally and in their forks. This
bullet-point is just for completion (not something we bother about here).
For (1): The `master` branch and `main` branch will locally exist. We should
ask to delete the `main` branch switch back to `master`. Then continue with
the full migration (with all other changes to the local git config)
For (2): We should run the migration as is (e.g. fetch main and set it up locally).
> fix(ng-dev): make `new-main-branch` command more flexible to local setup

- ng-dev/misc/new-main-branch/cli.ts
Do not throw if multiple remotes point to the Angular remote.
> fix(ng-dev): do not throw if multiple remotes point to angular remote

- ng-dev/release/notes/templates/changelog.ts
- ng-dev/release/notes/templates/github-release.ts
- ng-dev/release/publish/test/release-notes/generation.spec.ts
- tools/local-actions/changelog/main.js
Commits like the following were not captured properly because we only
assumed a single deprecation/breaking-change to be set on a commit.
> fix(ng-dev): release notes not capturing multiple note keywords from single commit

- .github/workflows/post-approval-changes.yml
Use the ANGULAR_ROBOT_PRIVATE_KEY for the post-approval-changes action
> build: fix post-approval-changes key

- github-actions/post-approval-changes/lib/main.ts
- github-actions/post-approval-changes/main.js
Previously the requested_teams was not spread resulting in an array like [[]] instead of [] when no reviews are pending.
> fix(github-actions): properly spread the requested_teams values for pending reviews

- ng-dev/pr/common/validation/failures.ts
- ng-dev/pr/merge/cli.ts
- ng-dev/pr/merge/task.ts
Using the `manual-branch-targeting` user's can choose to manually select the branches they would like to target rather than relying on the branches defined by the label.  This allows for one-off manual overrides of the logic we rely on. As noted in the warning at runtime, this does remove the attempts we make to guarantee that all commits are valid for the targeted branches.
> feat(ng-dev/pr): allow for manual override of targeted branches

- ng-dev/pr/discover-new-conflicts/cli.ts
- ng-dev/pr/rebase/cli.ts
Properly sets the rebase subcommand so it is accessible in the tooling.
> fix(ng-dev/pr): properly name the rebase command

- ng-dev/release/publish/actions/cut-release-candidate-for-feature-freeze.ts
- ng-dev/release/publish/test/common.spec.ts
Fixes #556.
@AndrewKushnir I kept the version at the end of the message since I want the "to-be-cut" version always easily discoverable. Hope that makes sense.
> refactor(ng-dev): include branch name for feature-freeze train for cut RC option

- ng-dev/BUILD.bazel
- ng-dev/cli.ts
- ng-dev/index.ts
- ng-dev/release/BUILD.bazel
- ng-dev/release/build/cli.ts
- ng-dev/release/cli.ts
- ng-dev/release/config/BUILD.bazel
- ng-dev/release/config/index.ts
- ng-dev/release/info/cli.ts
- ng-dev/release/precheck/BUILD.bazel
- ng-dev/release/precheck/cli.ts
- ng-dev/release/precheck/index.ts
- ng-dev/release/precheck/precheck.spec.ts
- ng-dev/release/publish/BUILD.bazel
- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/built-package-info.ts
- ng-dev/release/publish/external-commands.ts
- ng-dev/release/publish/test/branch-off-next-branch-testing.ts
- ng-dev/release/publish/test/delegate-test-action.ts
- ng-dev/release/publish/test/test-utils/action-mocks.ts
- ng-dev/release/publish/test/test-utils/staging-test.ts
- ng-dev/release/publish/test/test-utils/test-action.ts
- ng-dev/release/set-dist-tag/cli.ts
- ng-dev/utils/child-process.ts
- ng-dev/utils/read-stdin-until-closed.ts
- tools/local-actions/changelog/main.js
This commit introduces a new config option that can be defined to
configure custom release pre-checks that will run before releasing,
and after the release output has been built.
This allows for pre-release checks and post-build checks. Useful for
e.g. validating release output, checking the migration collection,
checking the peer dependency ranges etc.
> feat(ng-dev/release): support for custom release pre-checks to be provided

- ng-dev/release/publish/external-commands.ts
We always print `undefined` upon release pre-check errors. The actual
pre-check error messaging is piped from the child process to
stdout/stderr, and therefore the the `spawn` utility-thrown error
is not necessary to be printed.
> refactor(ng-dev): do not print `undefined` when release prechecks fail

- ng-dev/release/config/index.ts
- ng-dev/release/precheck/index.ts
- ng-dev/release/precheck/precheck.spec.ts
- ng-dev/release/publish/actions.ts
The `SemVer` class is bundled in `ng-dev`, like other dependencies. We should not
pass an object instance of `SemVer` to the user-customizable precheck function as it
would be easy for them to run into version-mismatch issues because SemVer utilities rely
heavily on `instanceof` checks.
e.g. in the COMP repo, we use `semver.compare` and passing the version from bundled
ng-dev in there, results in a runtime exception.
We should rather pass the string and expect users to parse it themselves in their own user-space.
> refactor(ng-dev): do not pass `SemVer` object to precheck function to avoid version mismatches

- renovate.json
We need to maintain a matching version of `glob` with the one provided by `protobufjs` since
protobufjs would otherwise throw. Similar to 405b6f6e874e6e297d00e8100bd0b5d31e00ea96
> build: prevent `glob` from being updated by renovate due to protobufjs limitation

- bazel/browsers/chromium/chromium.bzl
> fix(bazel/browsers): exclude unnecessary chromium file containing spaces on windows

- ng-dev/pr/checkout/cli.ts
In the `CommandModule` below we named the positional `<pr>`, but our
option does not reflect this. This causes the PR number to be not passed
to the GraphQL GitHub request. This happens due to a recent refactoring
that intended to standardize `pr` and `pr-number` to just `pr`.
> fix(ng-dev/pr): yargs positional placeholder does not match positional name

- bazel/integration/tests/angular-cli/BUILD.bazel
- bazel/integration/tests/playwright_chromium/BUILD.bazel
We have some non-RBE tests (to test platform-specific behavior), and
even within the sandbox, the shared Yarn cache is accesed. This can
result in errors as the folder might be accessed concurrently
(even though it should not be writable with Bazels sandbox)
https://app.circleci.com/pipelines/github/angular/dev-infra/306734/workflows/8ee6418f-cac4-489c-9d21-4baf6bf6b35b/jobs/309267/steps
> build: improve stability of concurrent integration tests running locally

- github-actions/commit-message-based-labels/main.js
- github-actions/slash-commands/main.js
- ng-dev/utils/config.ts
- tools/local-actions/changelog/main.js
Fixes errors like in:
https://app.circleci.com/pipelines/github/angular/dev-infra/307198/workflows/dd98537a-4142-459d-9942-43d17e832b7d/jobs/309755.
```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported 
by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```
> fix(ng-dev): ensure config can be properly loaded on windows

- ng-dev/cli.ts
- tools/local-dev.sh
Consumers should instead run `ts-node` as well. They need to pass in
the project manually anyway already, so it also makes this portion
easier by just having to directly use `ts-node` with `--project`.
> fix(ng-dev): avoid ts-node esm shebang that breaks on windows

- .circleci/setup-bazel.sh
- bazel/api-golden/test/BUILD.bazel
- bazel/api-golden/test/fixtures/BUILD.bazel
- bazel/spec-bundling/bundle-config.bzl
- bazel/spec-bundling/esbuild.config-tmpl.mjs
- bazel/spec-bundling/index.bzl
- bazel/spec-bundling/test/BUILD.bazel
- bazel/spec-bundling/test/core_invalid_linker_decl.spec.ts
Looks like the path is incorrect and we didn't run with RBE.
> build: fix remote execution not enabled on linux builds

- ng-dev/pr/common/targeting/labels.ts
- ng-dev/pr/config/index.ts
- ng-dev/pr/merge/integration.spec.ts
Until we have implemented the actual exceptional minor mechanism in both
the release and merge tool, we want to be able to turn `target: minor`
into `target: rc` (internally) so that minor changes can go into the
RC/FF phase that we "misuse" as the exceptional minor release train.
Primary reason for this is to avoid all the enforcement we provide for `target: rc` changes.
> feat(ng-dev): support exceptional minor target labeling in the interim

- README.md
Adds the CircleCI readme badge. Just making it easier to see the CI runs on e.g. mobile..
> build: add circleci readme badge

- github-actions/commit-message-based-labels/BUILD.bazel
- github-actions/commit-message-based-labels/action.yml
- github-actions/commit-message-based-labels/main.js
- github-actions/feature-request/BUILD.bazel
- github-actions/feature-request/action.yml
- github-actions/lock-closed/BUILD.bazel
- github-actions/lock-closed/action.yml
- github-actions/post-approval-changes/BUILD.bazel
- github-actions/post-approval-changes/action.yml
- github-actions/slash-commands/BUILD.bazel
- github-actions/slash-commands/action.yml
- github-actions/slash-commands/main.js
- tools/local-actions/changelog/BUILD.bazel
- tools/local-actions/changelog/action.yml
- tools/local-actions/changelog/main.js
We generate checked-in bundles with the default ESBuild `esnext`
target, while our actions are using Node 12, resulting in unsupported
syntax errors e.g. for the nullish coalescing operator.
> build: update all github actions to use node v16

- .github/workflows/ng-renovate.yml
We currently run Renovate from within `yarn renovate`. This results
in Yarn setting `YARN_IGNORE_PATH`. Since Renovate does not execute
in a docker isolated container, the environment variable will leak
through to our `yarn install` when e.g. the components repo is checked
out. Our dev-infra v2+ Yarn install would then always run because with
the environment variable, the vendored Yarn 1.x/ or the default Yarn 1.x
from the github action VM is simply ignored.
> refactor: fix renovate not respecting yarnrc paths

- package.json
- yarn.lock
The `re2` package is an optional dependency of `firebase-tools`
(transitively). It's super slow to build locally and also doesn't
seem to be cached locally, nor on CI. We should disable it as it
slows down the install by 1min.
Can be removed in the future with (worth checking) https://github.com/uhop/node-re2/issues/125
> build: skip building of bottleneck `re2` native dependency

- ng-dev/release/notes/context.ts
We now use the Angular robot for managing dependencies, and likely it
will be used more in the future. The bot commits should not end up
polluting release notes.
> refactor(ng-dev): do not capture Angular robot in release notes

- github-actions/org-file-sync/main.js
- github-actions/org-file-sync/src/main.ts
Adds logging to aide in diagnosing issues.
Additionally, when declaring the `repoSha` and `repoFileContent` values, set the default value explicitly as `undefined`.
When not initialized as `undefined`, the only set of the value is done without a `const` or `let` which allows the value
to escape the block it is defined in.  This results in the `sha` value in the API call to be incorrect because it uses a
previous files `sha` value, or the file content as well.
> fix(github-actions): add logging and set undefined for `repoSha` and `repoFileContent`

- tools/local-dev.sh
Similar to the `ts-node` fixes we landed in all repositories, we need to
use Node directly to not break the build-worker NodeJS fork invocation.
Also we disable type-checking when `yarn ng-dev` runs, for speed.
> build: speed up local `ng-dev` and fix release build command

- renovate.json
This folder cannot be updated as the dependencies need to
match 1:1 with the protobufjs CLI dependencies (which are installed
at runtime). This allows us to also remove the package excludes so
that we can update other dependencies outside of `tools/ts_proto`.
> build: exclude `tools/ts_proto` from renovate updates

- github-actions/post-approval-changes/lib/main.ts
- github-actions/post-approval-changes/main.js
The Angular Robot is used for Renovate, and when Renovate pushes a small
update / or rebases upon conflicts, we should not need another explicit
review.
All actions performed by the `angular-robot` are managed by Googlers, so
this account should be able to skip the post approval checks.
> feat(github-actions): skip angular-robot in postapproval action

- bazel/integration/test_runner/main.ts
- bazel/integration/test_runner/runner.ts
As it can be seen in the `main` branch, one integration test fails on
Windows. I just turned on this test to run on Windows.
The erorr is not something new, but it surfaces here in the dev-infra
repo because we use Yarn berry and Yarn 1.x. The intgeration test uses
Yarn 1.x. but our project itself uses Yarn Berry.
The integration test temporary directory (on Windows without the
sandbox, or on other platforms without the sandbox) resides within the
execroot directory, so that the `.yarnrc.yml` from the project is
inherited. This causes inconsistent test results on platforms and makes
integration tests rather non-hermetic (to an extent possible in
platforms without an actual FS sandbox).
We should fix this by always acquiring a test tmp directory in the
system temporary directories, not …
> fix(bazel): consistently run integration tests in sandbox-like directories

- bazel/remote-execution/BUILD.bazel
Explicitly specify the default remote pool as where all remote actions should run. This should in theory be a no-op right now because the remote execution instance only has one pool where all actions run anyway. However, specifying the pool for all actions will eventually become mandatory on RBE.
Not sure how to test whether this PR breaks Angular's remote builds.
> Specify worker pool in remote execution property

- ng-dev/caretaker/check/g3.spec.ts
- ng-dev/caretaker/check/g3.ts
It seems like multimatch previously did not throw when it received an
empty file path. We should never need to call multimatch with an empty
path, avoiding the runtime error. To fix this, we just do not
incorrectly try to derive diff information from an empty line if there
is no diff (this was a brittle logic).
> fix(ng-dev): do not throw if there is no diff between `g3` and `main`

- ng-dev/release/publish/actions/branch-off-next-branch.ts
- ng-dev/release/publish/test/branch-off-next-branch-testing.ts
This should make it clear to the caretaker (even though we have logging
for it already in the release tool and merge tool) that the final
branch-off PR needs to be merged..
> fix(ng-dev/release): wait for final branch-off PR before finishing release action

- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/actions/branch-off-next-branch.ts
- ng-dev/release/publish/actions/configure-next-as-major.ts
- ng-dev/release/publish/actions/cut-lts-patch.ts
- ng-dev/release/publish/actions/cut-new-patch.ts
- ng-dev/release/publish/actions/cut-next-prerelease.ts
- ng-dev/release/publish/actions/cut-release-candidate-for-feature-freeze.ts
- ng-dev/release/publish/actions/cut-stable.ts
- ng-dev/release/publish/constants.ts
- ng-dev/release/publish/prompt-merge.ts
- ng-dev/release/publish/pull-request-state.ts
- ng-dev/release/publish/test/branch-off-next-branch-testing.ts
- ng-dev/release/publish/test/common.spec.ts
- ng-dev/release/publish/test/configure-next-as-major.spec.ts
- ng-dev/release/publish/test/test-utils/action-mocks.ts
- ng-dev/release/publish/test/test-utils/staging-test.ts
- ng-dev/utils/testing/github-api-testing.ts
This PR introduces auto-merging for pull requests created by the release
tooling. This helps with:
* Avoids scenarios where the branches are in a state that would
throw-off other caretaker tooling. e.g. when the next update PR is not
merged after branching off.
* Avoiding confusion where the caretaker is not sure whether to use the
merge tool or how to merge the staging / cherry-pick PRs.
* Uncertainity where release-tool created PRs should go into. Do they
need a target label?
* Avoiding rate limit issues when e.g. staging PRs are left pending for
longer durations (e.g. people left it over night already). i.e. it
looks like Github may prevent connection if we query for PRs every 10 seconds /
or related `ETimedout` errors. Note: We still expect stable internet
connection as with bad …
> feat(ng-dev): automatically merge pull requests from within release tool 

- ng-dev/pr/common/targeting/target-label.ts
- ng-dev/pr/common/validation/pull-request-failure.ts
- ng-dev/pr/common/validation/validations.ts
- ng-dev/pr/merge/cli.ts
- ng-dev/pr/merge/failures.ts
- ng-dev/pr/merge/merge-pull-request.ts
- ng-dev/pr/merge/merge-tool.ts
- ng-dev/pr/merge/messages.ts
- ng-dev/pr/merge/pull-request.ts
- ng-dev/pr/merge/strategies/api-merge.ts
- ng-dev/pr/merge/strategies/autosquash-merge.ts
- ng-dev/pr/merge/strategies/strategy.ts
Cleans up the merge tool error handling by not passing through failures
and having uncaught errors at the same time. This results in confusion
and easily results in errors accidentally not being caught/handled
correctly.
Instead, we always use error try/catch and throwing similar to how its
done in the release tool. This is more safe, predictable and readable.
This is in preparation of fixing some of the force skip behavior of
the merge tool. This does currently not seem to work and broke at
some point..
> refactor(ng-dev): clean-up merge tool error handling in preparation for fixes

- .github/ng-renovate/runner-config.js
Allow downstream repositories to define Renovate post-upgrade tasks to be run after each upgrade. To keep a balance between security and flexibility, only commands that are defined as yarn scripts are allowed to be used as post-upgrade tasks
For more info on configuring post-upgrade tasks in Renovate, see:
- [postUpgradeTasks][1]
- [allowedPostUpgradeCommands][2]
- [allowPostUpgradeCommandTemplating][3]
[1]: https://docs.renovatebot.com/configuration-options/#postupgradetasks
[2]: https://docs.renovatebot.com/self-hosted-configuration/#allowedpostupgradecommands
[3]: https://docs.renovatebot.com/self-hosted-configuration/#allowpostupgradecommandtemplating
> ci: allow yarn scripts as Renovate post-upgrade tasks

- .github/ng-renovate/runner-config.js
The [allowedPostUpgradeCommands][1] pattern list is used to determine whether a [post-upgrade task][2] command is allowed to be run by Renovate. Using a regex to try and limit the type of commands that can be run is not a viable strategy.
This commit hard-codes the exact command that needs to run for angular.io docs examples dependencies (see angular/angular#47040).
Hard-coding commands requires updates in multiple places when a post-upgrade task is added/modified, but adds one more layer of protection against running unwanted commands as part of the Renovate update process.
[1]: https://docs.renovatebot.com/self-hosted-configuration/#allowedpostupgradecommands
[2]: https://docs.renovatebot.com/configuration-options/#postupgradetasks
> ci: hard-code allowed commands for Renovate post-upgrade tasks

- ng-dev/caretaker/check/github.spec.ts
- ng-dev/caretaker/check/github.ts
The URLs constructed by `caretaker/github.ts` were incorrectly escaped
and ended up e.g. not escaping a colon in URLs.
> fix(ng-dev): properly encode URLs for GitHub queries in caretaker check

- .github/ng-renovate/runner-config.js
The [allowedPostUpgradeCommands][1] pattern list is used to determine whether a [post-upgrade task][2] command is allowed to be run by Renovate. Having to explicitly allow each command creates unnecessary friction.
This commit allows any command to be run in a post-upgrade task, which saves us the trouble of having to update the allowed commands pattern list every time we want to add a new post-upgrade task.
Since adding/modifying Renovate post-upgrade tasks is subject to the regular PR review workflow, unwanted commands will be caught there.
##
_INFO: [Internal discussion][3]_
[1]: https://docs.renovatebot.com/self-hosted-configuration/#allowedpostupgradecommands
[2]: https://docs.renovatebot.com/configuration-options/#postupgradetasks
[3]: …
> ci: allow any command for Renovate post-upgrade tasks

- github-actions/create-pr-for-changes/action.yml
- github-actions/create-pr-for-changes/lib/main.ts
- github-actions/create-pr-for-changes/main.js
Previously, the `create-pr-for-changes` GitHub action would use the branch that the workflow was triggered on as the base branch. This prevented the action from being used on other branches as part of a [scheduled workflow][1], since scheduled workflows are only triggered on the default branch of a repository.
This commit adds the ability to specify a different base branch. If not specified, this defaults to the branch the workflow was triggered on, as before.
[1]: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
> feat(create-pr-for-changes): allow specifying a base branch

- bazel/remote-execution/BUILD.bazel
- bazel/remote-execution/index.bzl
> feat(bazel/remote-execution): expose exec_properties constant to enable networking on remote exec platform

- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/test/common.spec.ts
- ng-dev/release/publish/test/test-utils/action-mocks.ts
- ng-dev/release/publish/test/test-utils/test-action.ts
- ng-dev/release/publish/test/test-utils/test-utils.ts
There is an interesting scenario where the caretaker may make unexpected non-changelog changes as part of the short prompt where we allow manual polishing to the changelog.
If the caretaker modified other files there, they will NOT be part of the release cutting PR (and also shouldn't be) - but currently the changes are not discarded/or detected and WILL influence the release output building. This could cause subtle differences and confusion because the release output is different than what we committed (because the release cut commits will not incorporate the other non-changelog changes).
The fix is to properly detect other modifications and abort properly. Other changes should be made beforehand, go through review process and should not be part of the release cut commit.
> fix(ng-dev/release): avoid accidentally incorporating unexpected changes in release build

- bazel/browsers/browser_archive_repo.bzl
- bazel/browsers/chromium/chromium.bzl
This is a pre-req to the angular/universal Bazel migration underway in https://github.com/angular/universal/pull/2787
> build: add exports_files attribute to browser_archive for use downstream

- circleci-orb/BUILD.bazel
- circleci-orb/scripts/rebase-pr-on-target-branch/ref-branch-list.ts
This previously likely didn't surface because Git exec commands were silently accepted. Now with recent fixes- git failures actually result in the command failing
> fix(circleci-orb): do not cut off branch names with slashes

- circleci-orb/BUILD.bazel
- circleci-orb/commands/rebase-pr-on-target-branch.yml
- circleci-orb/scripts/rebase-pr-on-target-branch/ref-branch-list.ts
CircleCI cronjobs do not have the base revision or revision pipeline variables, so they may be empty. To avoid using empty variables which would then cause errors in our shared command- we support the empty string fallback. The command will be a noop anyway since we check for these variables in the actual script.
See: https://app.circleci.com/pipelines/github/angular/components/44462.
> fix(circleci-orb): support empty input parameters when e.g. running in cronjob

- github-actions/google-internal-tests/lib/main.ts
- github-actions/google-internal-tests/main.js
We also want to trigger for `opened` and `reopened` events.
> fix(github-actions): allow for other pull request event actions

- github-actions/feature-request/action.yml
Update the default labels for the feature request action to match the defined standard labels
> feat(github-actions): update the default labels used for feature request action

- .github/workflows/org-wide-actions.yml
Initially only set up the dev-infra repo confirm the sync works as expected.
> build: enable org wide action to sync labels

- github-actions/commit-message-based-labels/main.js
- github-actions/labels-sync/main.js
- ng-dev/pr/common/BUILD.bazel
- ng-dev/pr/common/labels/action.ts
- ng-dev/pr/common/labels/priority.ts
- ng-dev/pr/common/validate-labels.spec.ts
Github only allows for descriptions to be 100 characters, and as such, standard labels must comply with this requirement.
> refactor(ng-dev/pr): update standard label descriptions to be <= 100 characters

- package.json
- shared-scripts/angular-optimization/BUILD.bazel
- yarn.lock
The devkit brings in a lot of transitive dependencies and files, potentially pushing us over the RBE input file limit
As seen here:
https://app.circleci.com/pipelines/github/angular/angular/52508/workflows/a8803c49-42cc-455e-b06a-803f6ef2edca/jobs/1246870
We can reduce this by fine-grain selecting the files we need and managing its dependencies. These are only two dependencies and it's acceptable taking responsibility for it- especially since we have test coverage for it.
> fix(shared-scripts): cut down on dependencies from `@angular-devkit/build-angular`

- ng-dev/caretaker/check/services.spec.ts
- ng-dev/caretaker/check/services.ts
Add the status urls to the caretaker check for failing services to allow easier detail checks of the status for caretakers.
> feat(ng-dev/caretaker): add status urls to caretaker check

- github-actions/deploy-previews/pack-and-upload-artifact/action.yml
The Bazel directory for outputs are not writeable and for better convenience with using this action- the deploy contents should always be copied to not conflict with Bazel's permissions and output directory (and potential cache invalidation)
> feat(github-actions): move deploy directory to temporary directory to allow for editing

- github-actions/deploy-previews/pack-and-upload-artifact/action.yml
Using `644` without the `x` bit for directories means that the directory cannot be modified. i.e. no files can be created. We should not modify this bit but rather just ensure the folder is writeable and individual files have the `w` bit.
> fix(github-actions): only change temporary directory to ensure write access

- github-actions/deploy-previews/upload-artifacts-to-firebase/action.yml
TL;DR: There is no way to test GitHub actions directly 😓 
The wrong variables were used and the GitHub action did not even fail, but instead use some undefined value, causing the Firebase URLs to include some non-deterministic string.
Also the comment did not get posted because the PR number was not a valid one. Even here, the action did not print a failure..
> fix(github-actions): use proper variable names when accessing deploy metadata

- github-actions/branch-manager/lib/main.ts
- github-actions/branch-manager/main.js
Currently when a PR is retargeted, the assistant to the branch manager does not trigger an update.
cc. @alan-agius4 (this was the root cause for the stuck status in the renovate PRs I believe)
> fix(github-actions): update merge status when target label changes

- github-actions/deploy-previews/upload-artifacts-to-firebase/action.yml
This reduces the amount of preview channels we create, avoiding
quota issues. See: https://b.corp.google.com/issues/261985459
> fix(github-actions): only create a single preview channel per PR

- bazel/spec-bundling/esbuild.config-tmpl.mjs
Kudos to @josephperrott who found this back when we used ESBuild for legacy saucelabs bundle creation
https://angular-team.slack.com/archives/D0ZBU43EZ/p1636491354025800
> fix(bazel): spec-bundling rule should keep original names

- bazel/app-bundling/esbuild.config-tmpl.mjs
Fixes a typo that prevented non-entry-point files from being marked as side-effect free.
> fix(bazel): app bundle rule does not declare other files as side-effect free

- shared-scripts/angular-optimization/esbuild-plugin.mjs
There was another typo, preventing use of `isSideEffectFree`.
> fix(shared-scripts): properly use `isSideEffectFree` function

- bazel/spec-bundling/spec-entrypoint.bzl
- bazel/spec-bundling/test/BUILD.bazel
- bazel/spec-bundling/test/should_not_be_picked_up.spec.ts
Only specs part of the direct sources, or only direct init files should be considered by the rule.
Consider an example where one init file relies on another. The second init file should not be picked up as bootstrap file, but instead should just be loaded based on the direct `.init` file.
> fix(bazel): spec-bundle rule should never consider transitive files

- shared-scripts/angular-optimization/esbuild-plugin.d.ts
- shared-scripts/angular-optimization/esbuild-plugin.mjs
This can help up speeding builds as we wouldn't setup Babel if the linker is not needed for certain files.
> feat(shared-scripts): support only running linker on subset of files

- bazel/benchmark/driver-utilities/BUILD.bazel
`module_name` only has an effect for TS resolution and for the patched Bazel NodeJS resolution. The `package_name` equivalent is needed so that ESBuild or the Bazel NodeJS linker can map the name to the target.
> feat(bazel): allow for benchmark driver utilities to be linked

- bazel/http-server/server.ts
An actual file may be resolved, but with URL params. The params should be omitted when we resolve a file from the runfiles.
> fix(bazel): http server should support loading jsonp files

- bazel/spec-bundling/spec-entrypoint.bzl
- bazel/spec-bundling/test/BUILD.bazel
- bazel/spec-bundling/test/some_spec.js
This will be helpful for using the rule in `jasmine_node_test` where explicit specs may be passed through `srcs`.
> feat(bazel): support explicit files in spec-entrypoint

- bazel/spec-bundling/spec-entrypoint.bzl
- bazel/spec-bundling/test/BUILD.bazel
- bazel/spec-bundling/test/ensure-transitive-loaded.spec.ts
- bazel/spec-bundling/test/should_be_picked_up.spec.ts
- bazel/spec-bundling/test/should_not_be_picked_up.spec.ts
We recently switched all from transitive to just direct. We should keep this for the bootstrap code as there is a legitimate ordering issue if a bootstrap file depends on another and they would then be brought into with an unexpected order.
For specs we should consider all transitive ones too, just to be on the safe side of never missing any specs.
> feat(bazel): always consider transitive specs for spec-entrypoint

- .github/workflows/scorecard.yml
The scorecard action was failing for months. After looking into it, turns out the permissions were incorrectly set up and the signing failed because no id token was accessible..
> build: fix scorecard action failing

- .github/workflows/scorecard.yml
First of all, scorecard does not print a useful error at all. Looking through issues and their verify workflow logic, it seems like the permissions for the scorecard action workflow *need* to be set on the actual job itself, while the workflow-level permissions *cannot* contain any `write` permissions.
We already got further with the errors by enabling id-token write properly, but now the signing fails with an unknown error that we attempt to fix using this commit.
> build: fix scorecard signing by ensuring permissions are only set for job

- .circleci/publish_to_github.sh
A more obvious name, and matches other repositories.
> build: change snapshot build token variable to `SNAPSHOT_BUILDS_GITHUB_TOKEN`

- bazel/esbuild/index.bzl
This will remove the unnecessary files from most NPM packages relying on esbuild.
> feat(bazel): never build metafile by default in esbuild actions

- .github/local-actions/changelog/main.js
- ng-dev/release/notes/context.ts
The Angular robot can also use the name `angular-robot[bot]`. This name is now also included in the list of changelog robots and will be filter from changelogs.
> fix(ng-dev): filter alternate angular robot name from changelogs

- github-actions/create-pr-for-changes/lib/main.ts
- github-actions/create-pr-for-changes/main.js
Prior to this change superseded PRs remained open, now they are closed.
> fix(github-actions): close superseded PRs when using create-pr-for-changes

- .github/ng-renovate/yarn.lock
After the recent renovate PRs the lock file broke, likely due to manual edits in the Renovate PR.
> build: fix ng-renovate lock file after renovate

- ng-dev/BUILD.bazel
- ng-dev/index.ts
- ng-dev/release/stamping/_private_main.ts
- ng-dev/release/stamping/cli.ts
- ng-dev/release/stamping/env-stamp.ts
This allows downstream projects to have custom stamping properties along with the normal stamping. e.g. when a framework peer dependency variable for substitution should be computed based on the current project version.
> feat(ng-dev): allow for additional custom stamping

- .github/local-actions/branch-manager/main.js
- ng-dev/release/versioning/version-branches.ts
The Material infrastructure leveraged this function but we accidentally made it internal as part of the exceptional minor cleanup.
> feat(ng-dev): expose `convertVersionBranchToSemVer` function

- ng-dev/release/stamping/env-stamp.ts
This fixes a long-standing issue where the project version is emitted as a volatile key in stamping. This means that everytime a new version is put into `package.json`, the NPM package will not be rebuilt if it has been built previously.
This is the typical source of outdated NPM package artifacts where the package version is accidentally still the old one. The Bazel idiomatic fix is to use a `STABLE_` stamping key so that Bazel will properly re-build dependent targets whenever the version changes.
Ideally as part of larger future Bazel refactorings we would also make sure that only necessary target configurations depend on the stable status key file. Currently `ng_package`/`pkg_npm` always depends on it, even if there is no subsitution dependency on actual stable keys. …
> fix(ng-dev): always emit project version info as stable stamping keys

- .github/workflows/ng-renovate.yml
This is an effort to reduce `rate-limit-exceeded` errors and is also what is recommanded by Renovate folks.
See: https://github.com/renovatebot/renovate/discussions/16658
> ci: run renovate every 60 instead of 30 minutes

- .github/ng-renovate/runner-config.js
This commit disable Renovate from running on the `ngcc-validation` repository.
This is for a number of reasons including:
- NGCC is mainly in maintenance mode
- Failing Renovate PRs in these repo are not being checked
- This repo accounts for like 15% of our CircleCI credit usage
- This should help to reduce Github API `rate-limit-exceeded` errors
> ci: disable renovate for ngcc-validation repository

- .github/ng-renovate/runner-config.js
- .github/workflows/ng-renovate.yml
Renovate provides a way to cache repo data between runs using the `persistRepoData` option. This should help reduce `rate-limit-exceeded` errors in the renovate action which are causing it to fail silently.
See: https://docs.renovatebot.com/self-hosted-configuration/#persistrepodata
> ci: enable renovate cache

- .github/workflows/ng-renovate.yml
This value of this token is used by renovate to make authenticated calls when fetching release notes for repositories.
This should help reduce Github rate limit errors.
See: https://docs.renovatebot.com/getting-started/running/#githubcom-token-for-release-notes
> ci: set up `GITHUB_COM_TOKEN` in renovate config

- .github/ng-renovate/runner-config.js
A recommended approach to deal with github api secondary rate limit is to make requests concurrently.
See: https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28#dealing-with-secondary-rate-limits
> ci: limit concurrent requests to `api.github.com`

- github-actions/branch-manager/lib/main.ts
- github-actions/branch-manager/main.js
Branch manager occasionally fails due to secondary rate limit. Sometimes, almost 200 concurrent requests were performed.
Github recommends to make requests for a single user or client ID serially. See: https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28#dealing-with-secondary-rate-limits
Closes #961
---
**NB:** Currently, this workflow is disabled in [angular/angular](https://github.com/angular/angular/actions/workflows/assistant-to-the-branch-manager.yml), not sure if the limits was the reason behind this.
> fix(github-actions): do Github requests serially in branch manager

- github-actions/branch-manager/lib/main.ts
- github-actions/branch-manager/main.js
The branch manager logic for syncing merge ready PRs is flawed and currently always causes all PRs to be synced. This can be quite a lot, especially in repos like FW.
This caused queueing of GitHub actions in the dev-infra repo and slowed down updates of the mergeability status.
Related to: #998
> fix(github-actions): branch manager incorrectly syncs all PRs

- .circleci/config.yml
Update to use the gen2 executor for macos as the gen1 executor is being sunset in the coming months.
> ci: update macos executor to use gen2

- renovate.json
Renovate publishes on a per commit basis. We should try reducing PRs being merged in this repo as it would otherwise cause unnecessary PRs in downstream repos like framework.
> ci: reduce renovate updates

- .github/workflows/ci.yml
Currently when a PR lands in `main`, or when another PR is created, they all _always_ share the same concurrency group because the concurrency group `github.ref` is always the main branch due to `pull_request_target` being used.
We can fix this by switching to `pull_request` which also has the benefit of *NOT* executing user code in trusted VMs. Another benefit is that action config changes can be directly tested in PRs
> build: fix PR builds always getting cancelled

- .bazelrc
Currently we seem to be running with extremely limited concurrency, making Bazel builds take up to 10min.
> build: speed up remote execution builds on Github actions

- bazel/app-bundling/esbuild.config-tmpl.mjs
- bazel/spec-bundling/esbuild.config-tmpl.mjs
RxJS v6 does not match any conditions so we end up bundling the ES5 distribution which breaks surprisingly due to certain methods being missed on e.g. `Observable`.
We fix this by just preferring the more up-to-date distribution.
```
error: TypeError: observable2.logSubscribedFrame is not a function
at ColdObservable2._subscribe (file:///usr/local/google/home/pgschwendtner/.cache/bazel/_bazel_pgschwendtner/84e2b91096f108a3ead3e72250add8ed/sandbox/linux-sandbox/285/execroot/angular/bazel-out/k8-fastbuild/bin/packages/router/node_modules/rxjs/src/internal/testing/ColdObservable.ts:26:32)
at ColdObservable2.Observable2._trySubscribe (file:///usr/local/google/home/pgschwendtner/.cache/bazel/_bazel_pgschwendtner/84e2b91096f108a3ead3e72250add8ed/sandbox/linux-sandbox/285/execroot/angular/bazel-o …
```
> fix(bazel): spec bundling and app bundling breaking rxjs v6 testing code

- .github/ng-renovate/runner-config.js
This repo is in maintaince mode as it has it's content has been migrated into the CLI repo.
> ci: disable `angular/universal` from renovate updates

- github-actions/bazel/setup/action.yml
- github-actions/bazel/setup/add-repository-cache.sh
- github-actions/bazel/setup/setup-ci-bazelrc.mjs
* Re-enables some options that were lost from the CircleCI -> GHA migration, like color, verbose failures, and RC announcing
* Attempts to fix Bazel caching by not using tilde, but actually expanding the path into an absolute path. Similar to how it's done in CircleCI.
> feat(github-actions): improve CI bazel options when setting up bazel

- bazel/benchmark/component_benchmark/defaults/index.ts
`/dist/` is legacy and it will be removed in the next version
> fix(dev-infra): update `zone.js` import to use modern

- api-gen/rendering/entities.ts
- api-gen/rendering/entities/categorization.ts
- api-gen/rendering/entities/entry_template_map.ts
- api-gen/rendering/entities/renderables.ts
- api-gen/rendering/entities/traits.ts
- api-gen/rendering/index.ts
- api-gen/rendering/nunjucks_loader.ts
- api-gen/rendering/processing.ts
- api-gen/rendering/render-entities.ts
- api-gen/rendering/rendering.ts
- api-gen/rendering/templates/class-member-list.njk
- api-gen/rendering/templates/class-member.njk
- api-gen/rendering/templates/class.njk
- api-gen/rendering/templates/component-reference.njk
- api-gen/rendering/test/fake-entries.json
- api-gen/rendering/transforms/class-transforms.ts
- api-gen/rendering/transforms/jsdoc-transforms.ts
- api-gen/rendering/transforms/member-transforms.ts
Based on top of #1381.
This commit:
* Expands the processing of raw docs entries to "renderable" entries.
* Adds a nunjucks file loader that lets templates use macros
* Adds some actual templating for classes
> feat(api-gen): add more structure to the transform pipeline

- api-gen/extraction/test/BUILD.bazel
- api-gen/generate_api_docs.bzl
- api-gen/test/BUILD.bazel
This macro is a convenience for downstream repos to perform extraction and rendering with one API.
> feat(api-gen): add macro that combines api doc extraction and rendering

- api-gen/extraction/extract_api_to_json.bzl
- api-gen/extraction/index.ts
- api-gen/extraction/test/BUILD.bazel
- api-gen/generate_api_docs.bzl
- api-gen/rendering/entities/categorization.ts
- api-gen/rendering/entities/renderables.ts
- api-gen/rendering/entities/traits.ts
- api-gen/rendering/index.ts
- api-gen/rendering/processing.ts
- api-gen/rendering/rendering.ts
- api-gen/rendering/test/fake-entries.json
- api-gen/rendering/transforms/class-transforms.ts
- api-gen/rendering/transforms/module-name.ts
- api-gen/test/BUILD.bazel
Based on top of #1399
This commit adds `module_name` as an attribute to extraction, forwarding it along through the rest of the pipeline.
I'm not a huge fan of that way I've plumbed the moduleName through the pipeline here, but the only "clean" alternative I could come up with involved introducing a whole other set of `SomeDocEntry` that have the `moduleName` attached.
> feat(api-gen): add module_name to the pipeline

- api-gen/extraction/extract_api_to_json.bzl
- api-gen/extraction/index.ts
- api-gen/extraction/test/BUILD.bazel
- api-gen/extraction/test/fake-source.ts
- api-gen/generate_api_docs.bzl
- api-gen/test/BUILD.bazel
The latest `next` version of `@angular/compiler-cli` includes the new API, so we can now run it for real. This also adds an `entry_point` to the extraction rule, which is expected by the compiler-cli API.
> feat(api-gen): call getApiDocumentation to produce real output

- bazel/api-gen/extraction/extract_api_to_json.bzl
- bazel/api-gen/extraction/index.ts
- bazel/api-gen/extraction/test/BUILD.bazel
- bazel/api-gen/extraction/test/dummy-entry-point/BUILD.bazel
- bazel/api-gen/extraction/test/dummy-entry-point/index.ts
- bazel/api-gen/extraction/test/fake-source.ts
- bazel/api-gen/generate_api_docs.bzl
- bazel/api-gen/test/BUILD.bazel
Adds an `import_map` attribute to extract_api_to_json in order to enable resolving Angular packages, e.g. `@angular/core`. This is necessary for api extraction in order to fully resolve types when they're based on types in other packages.
> feat(api-gen): add `import_map` attr

- bazel/api-golden/find_entry_points.ts
- bazel/api-golden/test/fixtures/test_package/package.json
Currently, when a package export types field contain a wildcard the the api-golden step fails due to unsupported package name. This commit fixes this issue by not considering this as entry-point.
This fix is needed for https://github.com/angular/angular/pull/52080
> fix(bazel): do not error on `types` with wildcard

- .ng-dev/commit-message.mts
- bazel/BUILD.bazel
- bazel/markdown_to_html/BUILD.bazel
- bazel/markdown_to_html/index.ts
- bazel/markdown_to_html/markdown_to_html.bzl
- bazel/markdown_to_html/markdown_to_html.ts
- bazel/markdown_to_html/test/BUILD.bazel
- bazel/markdown_to_html/test/fake-markdown-source.md
- bazel/markdown_to_html/test/markdown_to_html.spec.ts
- bazel/private/path_relative_to_label.bzl
This commit adds a simple skeleton bazel rule and tests for rendering markdown to html with marked.
> feat(markdown-to-html): add skeleton for marked rendering

- .ng-dev/commit-message.mts
- bazel/markdown_to_html/BUILD.bazel
follow up fixes to the markdown to html PR.
> refactor(bazel): remove ESM bundling for markdown to HTML

- .github/local-actions/branch-manager/main.js
- .ng-dev/pull-request.mts
- ng-dev/pr/common/validation/assert-enforced-statuses.ts
- ng-dev/pr/common/validation/validate-pull-request.ts
- ng-dev/pr/common/validation/validation-config.ts
- ng-dev/pr/config/index.ts
This can be used in the future to enforce the unified status check, or to enforce additional thing. Right now it can be used to enforce some checks that aren't guaranteed to run otherwise.
In the future we may remove the configuration option and always default to the unified status check. This is the goundwork for future changes.
> feat(ng-dev): support enforcing certain checks to be running

- .github/local-actions/branch-manager/lib/main.ts
- .github/local-actions/branch-manager/main.js
The merge strategy now performs a real cherry pick but Git fails because there is no identity configured in Git.
> fix: branch manager breaking due to no git identity

- ng-dev/ts-circular-dependencies/config.ts
Fix issue with proprties in configuration are not writable when the config is in ESM format.
> fix(ng-dev): TypeError: Cannot assign to read only property 'baseDir' of object '[object Module]'

- bazel/api-gen/rendering/entities.ts
- bazel/api-gen/rendering/entities/categorization.ts
- bazel/api-gen/rendering/entities/renderables.ts
- bazel/api-gen/rendering/entities/traits.ts
- bazel/api-gen/rendering/processing.ts
- bazel/api-gen/rendering/rendering.ts
- bazel/api-gen/rendering/templates/header-api.tsx
- bazel/api-gen/rendering/templates/highlight-ts.tsx
- bazel/api-gen/rendering/templates/initializer-api-function.tsx
- bazel/api-gen/rendering/transforms/code-transforms.ts
- bazel/api-gen/rendering/transforms/initializer-api-functions-transform.ts
- bazel/api-gen/rendering/transforms/jsdoc-transforms.ts
- bazel/api-gen/rendering/transforms/member-transforms.ts
- bazel/api-gen/rendering/transforms/module-name.ts
Adds support for API generation of initializer APIs like the new `input`, `model`, `output` etc.
This commit:
* Updates `entities.ts` to match upcoming changes in the compiler to identify initializer APIs. Unfortunately cannot use the direct import yet- due to a circular dep.
* Adds a new renderable entry for initializer API
* Implements the rendering of the initializer API
* Fixes an issue where the `isDeveloperPreview` detection accidentally worked— but in practice is a field only for renderable entries.
* Syncs the `entities.ts` for other fields like `isNewType`
> feat(bazel): support api generation for initializer APIs

- .github/local-actions/changelog/main.js
- ng-dev/format/formatters/buildifier.ts
The buildifier `same-origin-load` warning is now obsolete and will be automatically applied when formatting. The presence of the warning name on the format command line will result in an error (`unexpected warning "same-origin-load"`) on newer versions of buildifier.
https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#same-origin-load
> fix(ng-dev/format): remove obsolete load-on-top buildifier warning

- docs/package.json
This is required by the docs pipeline
Should fix https://github.com/angular/angular/issues/55657
> fix(shared-docs): add missing `mermaid` dep

- bazel/api-gen/extraction/BUILD.bazel
- bazel/api-gen/manifest/BUILD.bazel
- bazel/api-gen/rendering/BUILD.bazel
- bazel/api-golden/BUILD.bazel
- bazel/benchmark/component_benchmark/component_benchmark.bzl
- bazel/benchmark/driver-utilities/BUILD.bazel
- bazel/defaults.bzl
- bazel/http-server/BUILD.bazel
- bazel/integration/test_runner/BUILD.bazel
- bazel/map-size-tracking/BUILD.bazel
- bazel/test/BUILD.bazel
Currently the default `target` for the code compiled with `ts_library` is set through the `ts_library` exposed in `defaults.bzl`, however the code under the `bazel` directory isn't allowed to use `defaults.bzl` which meant that it was defaulting to es2015.
These changes add a `defaults.bzl` specific to the `bazel` directory which allows us to maintain the defaults in a single place.
This came up due to a breakage in https://github.com/angular/angular/pull/56096.
> build: set es2020 in bazel ts_library usages

- bazel/BUILD.bazel
Fixes that the `defaults.bzl` from #2084 wasn't included in the npm package.
> build: add missing file to npm output

- github-actions/linting/licenses/dependency-review-config.yml
google-protobuf is licensed under a combination of two licenses: Apache-2.0 and BSD-3-Clause.
> fix(github-actions): allow `Apache-2.0 AND BSD-3-Clause` license

- .github/workflows/ng-renovate.yml
This version of runner uses Node.js 20 by default which is needed by Renovate.
```
Unsupported node environment detected. Please update your node version
```
See: https://github.com/actions/runner-images/issues/9848 and https://github.com/angular/dev-infra/actions/runs/10139617149
> ci: update renovate workflow to use `ubuntu-24.04` as runner

- bazel/spec-bundling/esbuild.config-tmpl.mjs
- bazel/spec-bundling/spec-bundle.bzl
This update prevents the inclusion of esbuild optimization plugins when both linking and downleveling are disabled. It also removes //shared-scripts/angular-optimization:js_lib from the spec-bundle unless explicit linking is required. This change addresses a circular dependency issue previously observed with this rule in the Angular CLI, leading to the removal of a related patch. For more details, see: https://github.com/angular/angular-cli/blob/3c9697a8c34a5e0f3470bde73f11f9f32107f42e/.yarn/patches/%40angular-build-tooling-https-06f4984cdf.patch
> fix(bazel): conditionally add esbuild optimization plugins

- github-actions/linting/licenses/dependency-review-config.yml
Add `CC-BY-3.0` as a license we allow to be used in our dependencies
> fix(github-actions): add `CC-BY-3.0` as a permissible license

- ng-dev/release/config/index.ts
- ng-dev/release/publish/BUILD.bazel
- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/external-commands.ts
Updating the `package.json` for a release also requires updating some Aspect lock files that
capture the hash of the `package.json` file.
The release tool currently doesn't do this, and some tricky manual workaround steps are
needed. This commit automatically runs the sync command.
> feat(ng-dev): support releasing when operating in a hybrid pnpm rules_js repo

- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/actions/configure-next-as-major.ts
- ng-dev/release/publish/actions/exceptional-minor/prepare-exceptional-minor.ts
- ng-dev/release/publish/actions/shared/branch-off-next-branch.ts
Several actions within the release process were not committing the aspect lock files as expected. This fix ensures that the aspect lock files are properly committed during all relevant stages of the release workflow.
> fix(ng-dev): ensure release actions commit aspect lock files

- ng-dev/commit-message/validate.spec.ts
- ng-dev/commit-message/validate.ts
Some repositories do not allow fixup commits. This feature adds a configuration option to disallow such commits during the validation process.
> feat(ng-dev): introduce an option to disable fixup commits in commit validation

- ng-dev/commit-message/config.ts
- ng-dev/commit-message/validate.spec.ts
- ng-dev/commit-message/validate.ts
This option needs to be configurable from the config
> fix(ng-dev): move `disallowFixup` to commit message config

- ng-dev/index.ts
This is useful for the docs deployment script in Material, where we currently have two different Yarn versions.
> feat(ng-dev): expose utilities for resolving yarn

- ng-dev/package.json
The package depends on `which` but did not explicitly list it as a direct dependency, leading to build failures.
The following error was encountered during the build:
```
ERROR: <path-to-file>/BUILD.bazel:7:19: Bundling Javascript <path-to-file>/lib/main.ts [esbuild] failed: (Exit 1): _main_generated_esbuild_launcher.sh failed: error executing command
Error: Could not resolve "which"
node_modules/@angular/ng-dev/utils/resolve-yarn-bin.js:10:18:
import which from 'which';
~~~~~~~
```
Example: https://github.com/angular/angular/actions/runs/12997612455/job/36248972584?pr=59669
> fix(ng-dev): add `which` to direct dependencies

- ng-dev/release/publish/external-commands.ts
In certain scenarios, running `bazel run @npm2//:sync` does not reliably update the aspect lock files. For example:
```
$ yarn bazel run @npm2//:sync  # Lock file is updated
$ git restore .aspect
$ yarn bazel run @npm2//:sync  # Lock file is NOT updated
```
Switching to `bazel sync --only=repo` guarantees that the lock file is consistently updated.
More context: https://angular-team.slack.com/archives/C042EU9T5/p1739398554132249
> fix(ng-dev): replace `bazel run @npm2//:sync` with `bazel sync --only=repo`

- ng-dev/release/publish/external-commands.ts
> fix(ng-dev): handle error when running `bazel sync --only=repo`

- .github/workflows/ci.yml
Follow-up to #2576 
NOTE: This does not mean we are no longer supporting contributing to Angular on a Windows machine. Instead, we are working towards having a more stable and guaranteed developer experience on Windows! We will still ensure and verify that the Angular CLI (`ng`) works on Windows!
---
Many contributors and team members are using Linux or MacOS for development of Angular. Our tooling regularly faces challenges with infrastructure needing extra work and tricks just to function to some extent on Windows. E.g. shell scripts or Bazel actions that need extra layers for batch files that spawn a Bash shell etc, or inconsistent escaping across shells. This is putting extra stress on our infrastructure team, results in in unnecessary complexity and slows down overall development …
> build: remove windows testing and CI setup

- github-actions/setup-wsl/action.yml
This makes the downstream job code much simpler and more readable.
> feat(github-actions): expose more common information in `setup-wsl` action

- github-actions/setup-wsl/action.yml
This is necessary as otherwise the composite action is broken.
> fix(github-actions): composite actions need explicit `shell`

- github-actions/npm/checkout-and-setup-node/action.yml
This is a useful addition to the shared checkout action that will help integrating with Windows support.
> fix(github-actions): do not auto convert to CRLF when checking out

- github-actions/setup-wsl/action.yml
This is an attempt to avoid surprising errors when launching too many processes from within WSL to "emulate native Windows testing".
See: https://github.com/Mozilla-Ocho/llamafile/issues/491
> feat(github-actions): increase WSL memory

- github-actions/setup-wsl/action.yml
This will be useful for e.g. 2025 Windows images that seemingly have a different interface name.
> feat(github-actions): allow for WSL firewall interface to be configurable

- github-actions/setup-wsl/action.yml
This will be useful if we want to try the WSL2 mirrored network mode, that merges both "hosts" into a single "localhost".
> feat(github-actions): support configuring networking mode for WSL action

- github-actions/setup-wsl/action.yml
WSL actions don't benefit much from the default setup-node action and caching, so we should have our own caching to speed up jobs and improve stability. This commit adds this functionality.
> feat(github-actions): add caching to WSL environment

- bazel/git-toolchain/BUILD.bazel
- bazel/remote-execution/BUILD.bazel
This allows us to compile the Angular CLI tests for Windows target platform, allowing us to execute the CLI tests outside Bazel in native Windows environments.
> feat(bazel): still support cross-compiling for Windows

- bazel/package.json
- bazel/pnpm-lock.yaml
- bazel/spec-bundling/index_rjs.bzl
- bazel/spec-bundling/spec-entrypoint.bzl
- github-actions/bazel/configure-remote/BUILD.bazel
This is an initial, and still sufficient version of spec bundling for `rules_js`. Notably it's significantly shorter and very clean. Very convincing to see this short code snippet for a previously rather complicated piece.
We will continue to need spec bundling for ESM Karma tests. This is expected and even speeds up tests significantly, and improves stability.
> feat(bazel): support spec bundling with `rules_js`

- .github/ng-renovate/yarn.lock
Currently the installation is failing as the lock file is not correctly synced.
> build: update lock file

- github-actions/npm/checkout-and-setup-node/action.yml
The regex was accidentally matching `npm` out of `pnpm`.
> fix(github-actions): pnpm detection accidentally matching `npm`

- bazel/spec-bundling/index_rjs.bzl
- github-actions/setup-wsl/action.yml
The user, consuming the action, should be responsible for installing pnpm, or yarn.
> Various fixes for Angular CLI migration

- .github/workflows/ng-renovate.yml
This is the minimum required version in the Angular CLI repo.
```
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)
Your pnpm version is incompatible with "/tmp/renovate/repos/github/angular/angular-cli".
Expected version: ^9.15.6
Got: 9.15.4
This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.
To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
```
> ci: update renovate pnpm to `9.15.6`

- bazel/api-golden/test/fixtures/test_package/shared_chunk.d.ts
- bazel/api-golden/test/fixtures/test_package/testing/index.d.ts
- bazel/api-golden/test/fixtures/test_package/testing/nested.d.ts
- bazel/api-golden/test/goldens/test_package/testing/index.api.md
- bazel/api-golden/test/goldens/test_package/testing/nested/index.api.md
This verifies that shared `.d.ts` chunks work properly in API golden testing. It's fine (and keeps the code simple) to just expect the shared definition to be repeated in the package entry-point goldens (it's still a single command to update)
> test(bazel): ensure shared chunks work properly in API golden testing

- ng-dev/utils/BUILD.bazel
- ng-dev/utils/constants.ts
- ng-dev/utils/version-check.ts
- package.json
- tools/local-dev.sh
- yarn.lock
Currently we only check `yarn.lock`, but in e.g. CLI we already removed the yarn lock file.
> fix(ng-dev): check pnpm lock for latest `ng-dev` version when running release tool

- ng-dev/release/publish/external-commands.ts
pnpm invoked via `npx` currently can bloat stdout and break the release tool. This commit fixes this.
> fix(ng-dev): ensure pnpm is silent when invoked as external command

- bazel/api-golden/index_npm_packages.ts
This makes it much easier to generate the initial golden directory, as we don't have to manually create all of them, for every entry-point.
> fix(bazel/api-golden): ensure golden directory exists

- bazel/api-golden/index_npm_packages.ts
This allows us to approve goldens even if the files don't exist yet.
> fix(bazel/api-golden): do not try to read golden in approve mode

- ng-dev/caretaker/handoff/update-github-team.ts
This will be useful as currently EMEA caretaker permissions were manually handled.
> feat(ng-dev): support EMEA caretaker in `ng-dev handoff`

- github-actions/linting/licenses/dependency-review-config.yml
Explicitly ignore renovate for license check as we have determined an exception for this package. Additionally use hyphen separators instead of underscores based on new documentation.
> fix(github-actions): explicitly allow renovate as a dependency through the license check

- .github/local-actions/branch-manager/main.js
- .github/local-actions/labels-sync/main.js
- github-actions/branch-manager/main.js
- github-actions/commit-message-based-labels/main.js
- github-actions/unified-status-check/main.js
- ng-dev/pr/common/labels/merge.ts
This label and its merge script mode don't work properly with auto-squash. The label was initially built in the components repository; which doesn't use autosquashing.
We should not re-add the label automatically.
> build: remove fix commit message label as it breaks with autosquash strategy

- bazel/spec-bundling/index_rjs.bzl
This will be useful when tests assert on e.g. class `constructor.name` fields.
> fix(bazel): improve spec bundling to preserve original names

- bazel/spec-bundling/index_rjs.bzl
Support `config` in `spec-bundle` rule. This is useful for supporting e.g. path mappings.
> feat(bazel): support more options in spec-bundle rule

- bazel/spec-bundling/index_rjs.bzl
Currently we don't have any real TS-based errors because source-maps aren't linked.
> fix(bazel): ensure source maps for spec-bundle is linked

- bazel/api-golden/BUILD.bazel
- bazel/api-golden/index_npm_packages.ts
- bazel/api-golden/test_api_report.ts
- bazel/package.json
- bazel/pnpm-lock.yaml
Speeds up golden testing by parallelizing. This got it down from
~85second of e.g. Material golden testing to 15seconds!
> build: speed up golden testing by parallelizing

- bazel/spec-bundling/spec-entrypoint.bzl
We didn't bring in transitive npm sources. This commit fixes this, so that we can now e.g. import zone.js in bootstrap spec-bundling files.
> fix(bazel): ensure spec-bundling supports npm dependencies

- bazel/http-server/main.ts
This will be useful for a more generic `server_test` rule.
> feat(bazel): support `PORT` environment variable in http_server

- ng-dev/pr/rebase/index.ts
The env variable is only needed with autosquash. Otherwise the editor will not be presented.
> fix(ng-dev): fix interactive rebase env

- bazel/http-server/main.ts
This is necessary for `server_test` to override the port that may be specified via Starlark, or the CLI flag.
> fix(bazel): ensure `PORT` variable is prioritized over CLI flag

- .bazelrc
- bazel/http-server/BUILD.bazel
- bazel/http-server/ibazel.mts
- bazel/http-server/index.bzl
- bazel/http-server/launcher_template.sh
- bazel/http-server/main.mts
- bazel/http-server/server.mts
- bazel/http-server/test/BUILD.bazel
- bazel/http-server/test/server-test.ts
- bazel/http-server/test/tsconfig.app.json
- bazel/package.json
- bazel/pnpm-lock.yaml
Updates the `http_server` to work with `rules_js`.
> feat(bazel): update `http_server` to work with `rules_js`

- .github/workflows/ng-renovate.yml
This job is currently broken due to an older Node.js version being installed.
See: https://github.com/angular/dev-infra/actions/runs/14835918390/job/41647050107
> ci: update ng-renovate to use `ubuntu-latest`

- .github/workflows/ng-renovate.yml
This repo only has a single dependency and the update PR never gets merged https://github.com/angular/.github/pull/32
> ci: remove `angular/.github` for auto update

- github-actions/create-pr-for-changes/lib/main.ts
- github-actions/create-pr-for-changes/main.js
When using the `create-pr-for-changes` workflow, old branches are not being deleted, and the content of superseded PRs remains open. This change ensures that:
- Obsolete branches are deleted after PR creation.
- Previously created PRs with outdated content are automatically closed.
Example: https://github.com/angular/angular/pull/61203
> fix(github-actions): delete obsolete branches and close superseded PRs

- .github/workflows/ng-renovate.yml
Turns out we cannot use corepack as not all package.json have a packageManager field.
Ex: https://github.com/angular/angular/pull/61234#issuecomment-2867330185
> Corepack revert

- ng-dev/release/publish/actions/renovate-config-updates.ts
- ng-dev/release/publish/actions/shared/branch-off-next-branch.ts
Adds support for automatically modifying `renovate.json` to include newly created branches in the `baseBranches` array, when `updateRenovateConfig` is enabled.
> feat(ng-dev): update `renovate.json` baseBranches when creating a new branch

- renovate-presets/default.json5
- renovate.json
Introduce a Renovate configuration file with grouped update strategies, off-peak scheduling, semantic commit formatting, and workflow-specific rules. Key features include:
- Grouping of non-major, Bazel, Angular, and TypeScript dependencies
- Custom scheduling for weekdays and weekends in America/Tijuana timezone
- PR concurrency and hourly limits to control Renovate behavior
- Exclusion rules for placeholder versions and major updates on select packages
- Enable lock file maintenance and use of semantic commit messages
See associated pull request for more information.
> ci: add comprehensive configuration for renovate dependency automation

- renovate-presets/default.json5
> ci: ignore `yarn` & `bazel` updates

- ng-dev/format/formatters/prettier.ts
- renovate-presets/default.json5
> refactor: configure prettier to format json5

- renovate.json
From taking to Paul it appears that this is no longer needed.
> ci: remove `yarn bazel sync --only=repo || true`

- renovate-presets/default.json5
This change ensures that `angular/dev-infra` update in WORKSPACE files is grouped with `cross-repo angular dependencies` instead of `bazel` to reduce the amount of PRs opened.
> fix(github-actions): move `angular/**` to `matchPackageNames`

- renovate-presets/default.json5
- `matchDepNames` conflicts with `matchDepNames`
- `@angular/benchpress` is not released as `next` this is causing a dependency lookup warning
> fix(github-actions): more `cross-repo angular dependencies` fixes

- bazel/browsers/chromium/chromium.json
- bazel/remote-execution/BUILD.bazel
We should try if we can work without this.
> refactor: remove docker sys_admin capability

- ng-dev/misc/generated-files/update-generated-files.ts
Previously, if an error occurred, the spinner was never stopped, preventing the task from completing. As a result, Renovate would hang for several minutes before being forcefully terminated.
> fix(ng-dev): ensure `update-generate-files` completes on error

- .github/workflows/ng-renovate.yml
Currently, the postinstall `yarn ng-dev misc update-generated-files` is too slow for `angular/angular` which causes Renovate to be slow. This is a tenative fix by using more CPUs.
> ci: use `ubuntu-latest-4core` for Angular renovate

- .github/workflows/ng-renovate.yml
This reverts commit 2ccf1247420ab72d27e99ee5e585156934596f5a.
For the logs it appears that this did not improve much.
> Revert "ci: use `ubuntu-latest-4core` for Angular renovate"

- renovate.json
Not sure what changed overnight, but Renovate is now committing .npmrc files that we didn't generate.
Example: https://github.com/angular/angular/pull/61492/files
We should revisit this once we transition away from Yarn.
> ci: clean untracked files before running `postUpgradeTasks`

- renovate-presets/default.json5
This package always get released as a major version, and sometimes it's released multiple time per day https://www.npmjs.com/package/google-closure-compiler?activeTab=versions
> ci: reduce schedule for `google-closure-compiler`

- github-actions/commit-message-based-labels/lib/main.ts
- github-actions/commit-message-based-labels/main.js
If a commit message does not match our patterns and a label has already been applied manually, this action would remove the labels, which would add the PR back to the triage queue. Instead, this will never remove an already added label.
> refactor(github-actions/commit-message-based-labels): prevent auto removal of already applied labels

- renovate.json
This reverts commit 392eb3948a25a7d82a10b9af12b563fe21107587 as the issue was addressed upstream.
> Revert "ci: clean untracked files before running `postUpgradeTasks`"

- WORKSPACE
- tools/bazel-patches/build_bazel_rules_nodejs.patch
This is the min supported version of Angular 20
> build: update node.js toolchain to use `20.19.0`

- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/test/common.spec.ts
- ng-dev/utils/prompt.ts
The error and aggresive failing, even with a single retry caused a few issues in the past. This commit tries to make this more robust and failure tolerant.
> fix(ng-dev): allow for graceful retries when GitHub API is outdated

- github-actions/pull-request-labeling/lib/main.ts
- github-actions/pull-request-labeling/main.js
This prevents items being added to the merge queue accidentally still in draft mode.
> refactor(github-actions): Updated metadata labeler to remove merge label when PR is in draft

- ng-dev/ai/consts.ts
Switches from using the `flash` model to the `pro` one by default.
> fix(ng-dev): default model to pro

- ng-dev/release/publish/actions.ts
Renovate uses the configuration file in the main branch, thus the label changes need to be commited to the `main` branch and not the release branch.
> fix(ng-dev): cherry-pick renovate config label changes

- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/test/common.spec.ts
Prerelease is not a boolean but rather an array.
> fix(ng-dev): fix prerelease check in `cherryPickChangelogIntoNextBranch`

- .github/ng-renovate/runner-config.js
- renovate-presets/default.json5
This is needed as a workaround for PNPM due which causes the lock file to be broken due to Renovate passing `--ignore-pnpmfile`
Example: https://github.com/angular/angular/pull/62935/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL13
See: https://github.com/renovatebot/renovate/discussions/30812
> build: allow scripts during renovate update

- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/external-commands.ts
Currently the release process hangs due to PNPM being interactive `The modules directories will be removed and reinstalled from scratch. Proceed? (Y/n) ` if when pressing `yes` the process does not continue.
Also, there is no reason why using `npx` to invoke `pnpm` as when having pnpm version 10 locally the correct version of pnpm will be downloaded.
> fix(ng-dev): fix release issues with PNPM

- ng-dev/release/publish/actions.ts
- ng-dev/release/publish/actions/configure-next-as-major.ts
- ng-dev/release/publish/actions/exceptional-minor/prepare-exceptional-minor.ts
- ng-dev/release/publish/actions/shared/branch-off-next-branch.ts
- ng-dev/release/publish/external-commands.ts
- ng-dev/utils/constants.ts
This lock has contains hashes of the package.json file. Thus it needs to be updated once the version is updating during the release.
> feat(ng-dev): handle updating the `MODULE.bazel.lock` file during a release

- github-actions/bazel/setup/action.yml
- github-actions/bazel/setup/setup-ci-bazelrc.mjs
> Bazel setup and cache fixes.

- github-actions/setup-wsl/action.yml
This commit introduces a caching mechanism for NVM installations within the GitHub Actions workflow.
> feat(github-actions): cache nvm installations between runs

- github-actions/npm/checkout-and-setup-node/action.yml
The actions/setup-node step now includes a disable-pnpm-cache input. This resolves an issue where actions/cache would cause the workflow to fail on certain environments, such as WSL, due to being unable to locate the pnpm cache store.
> fix(github-actions): provide an option to disable pnpm cache

- renovate-presets/default.json5
This commit updates the Renovate schedule in to 'Every minute, every 2 hours'. This change is intended to adjust the frequency of Renovate's operations, using a cleaner and more human-readable format.
> ci: update renovate schedule
